#!/usr/bin/env node
/**
 * Acceptance runner.
 *
 * Boots the plugin in a real, isolated DSH profile and drives one case through
 * the host's own IPC channel to `ctx.flow`. Every artifact lands in
 * `.artifacts/<run-id>/`; the report separates mechanism failures from model
 * output quality and environment problems.
 *
 * Usage:
 *   node acceptance/run.mjs --case <case> --run-id <id>
 *     [--mode hierarchical|flat|single|all] [--timeout-ms N]
 *     [--budget-scale N] [--max-role-turns N] [--keep-host]
 */
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, readlinkSync, realpathSync, writeFileSync, readdirSync, existsSync, rmSync, statSync, symlinkSync, unlinkSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DshHost, buildHostEnv, CASE_ENV_KEYS, createRunLayout, ensureProfile, WEB_PROFILE_BUNDLES, PROJECT_ROOT } from './lib/host.mjs';
import { writeScopeAnalysis } from './lib/ledger.mjs';
import { startMockModel } from './lib/mock-model.mjs';
import { buildScenario } from './lib/mock-scenarios.mjs';

const CASES_DIR = join(PROJECT_ROOT, 'acceptance/cases');
const CHECKS_DIR = join(PROJECT_ROOT, 'acceptance/checks');
const ARTIFACTS_ROOT = join(PROJECT_ROOT, '.artifacts');

/** The route and model a mock run uses; both are fixture-owned, never ambient. */
export const MOCK_PROVIDER = 'mock-local';
export const MOCK_MODEL_ID = 'mock-model';
export const MOCK_API_KEY = 'acceptance-mock-key';

/**
 * The run's own model overlay. It is written into the run directory (never into
 * `examples/`) and appended last, so a mock run cannot silently inherit the
 * remote or local-service route the case names.
 *
 * The shape mirrors the deployment's working provider block — a profile that
 * declares no thinking level above "off" is refused by the provider's own
 * catalog, so the model entry keeps the same two levels the shipped routes use.
 */
export function mockPatchText(baseURL) {
  return `# Generated by acceptance/run.mjs --mock for one run. Do not edit.
- id: llm-pi-ai
  config:
    providers:
      ${MOCK_PROVIDER}:
        displayName: Acceptance mock (deterministic fixture)
        api: openai-completions
        baseURL: ${baseURL}
        headers:
          Authorization: Bearer ${MOCK_API_KEY}
        timeoutMs: 120000
        streamIdleTimeoutMs: 60000
        retryPolicy:
          mode: normal
          maxRetries: 0
        compat:
          thinkingFormat: qwen-chat-template
          supportsStore: false
          supportsDeveloperRole: false
          supportsReasoningEffort: false
          supportsStrictMode: false
          supportsUsageInStreaming: true
          maxTokensField: max_completion_tokens
        models:
          - id: ${MOCK_MODEL_ID}
            contextWindow: 131072
            maxTokens: 4096
            input: [text]
            reasoningEfforts:
              off:
              high: high
- id: agent-default-model
  config:
    provider: ${MOCK_PROVIDER}
    model: ${MOCK_MODEL_ID}
    reasoningEffort: off
`;
}

const MODE_LIMITS = {
  hierarchical: {},
  flat: { max_depth: 1, max_children: 32 },
  single: { max_depth: 1, max_children: 1 },
};

async function main() {
  const args = parseArgs(process.argv.slice(2));
  for (const key of ['budget-scale', 'max-role-turns']) {
    if (args[key] !== undefined && (!Number.isSafeInteger(args[key]) || args[key] < 1)) {
      throw new Error(`--${key} must be a positive integer`);
    }
  }
  const caseDef = loadCase(args.case);
  const runIds = args.mode === 'all' ? ['single', 'flat', 'hierarchical'] : [args.mode ?? 'hierarchical'];
  const summaries = [];
  for (const mode of runIds) {
    const runId = runIds.length > 1 ? `${args['run-id']}-${mode}` : args['run-id'];
    summaries.push(await runOnce({ args, caseDef, mode, runId }));
  }
  const failed = summaries.filter(summary => summary.scenario_status !== 'PASSED');
  console.log(JSON.stringify({ case: caseDef.id, runs: summaries }, null, 2));
  if (failed.length && !args['keep-failed']) process.exitCode = 1;
}

function parseArgs(argv) {
  const out = { mode: 'hierarchical', 'timeout-ms': undefined };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const next = argv[index + 1];
    if (next === undefined || next.startsWith('--')) out[key] = true;
    else {
      out[key] = /^-?\d+$/.test(next) ? Number(next) : next;
      index += 1;
    }
  }
  return out;
}

/**
 * The only case-level environment a case may set. Isolation (`HOME`, `TMPDIR`,
 * `DSH_HOME`), the data directory, the workspace and the model route are owned
 * by the runner: a case that could redirect them would stop being a case and
 * start being a different experiment.
 */
export { CASE_ENV_KEYS };

export function validateCaseEnv(caseDef) {
  const env = caseDef.env ?? {};
  if (typeof env !== 'object' || Array.isArray(env)) throw new Error(`case ${caseDef.id}: env must be an object`);
  const unknown = Object.keys(env).filter(key => !CASE_ENV_KEYS.includes(key));
  if (unknown.length) {
    throw new Error(`case ${caseDef.id}: env may only set ${CASE_ENV_KEYS.join(', ')}; got ${unknown.join(', ')}`);
  }
  for (const [key, value] of Object.entries(env)) {
    if (typeof value !== 'string' || !value) throw new Error(`case ${caseDef.id}: env.${key} must be a non-empty string`);
  }
  return env;
}

export function modelRouteFromEnv(env = process.env) {
  return {
    baseURL: env.FLOW_MODEL_BASE_URL ?? env.FLOW_QWEN_BASE_URL ?? 'http://127.0.0.1:8000/v1',
    model: env.FLOW_MODEL_ID ?? env.FLOW_QWEN_MODEL ?? 'Qwen3.8-27B-FP8',
    provider: env.FLOW_MODEL_PROVIDER ?? 'local-sglang',
  };
}

function hashText(text) {
  return `sha256:${createHash('sha256').update(text).digest('hex')}`;
}

function hashFile(path) {
  return existsSync(path) ? hashText(readFileSync(path)) : null;
}

/** One digest over every file of a source tree, plus its file count. */
function hashTree(root) {
  if (!existsSync(root)) return { digest: null, files: 0 };
  const files = walk(root).map(entry => ({ path: entry.path, digest: hashFile(entry.path) }))
    .sort((a, b) => a.path.localeCompare(b.path));
  const digest = hashText(files.map(entry => `${entry.path}:${entry.digest}`).join('\n'));
  return { digest, files: files.length };
}

/**
 * The code fingerprint of one run: the plugin sources, both built entry points,
 * the case file and every patch the host loads. It is what makes "the same
 * build" a checkable claim instead of an assumption.
 */
/**
 * Which part of the build fingerprint moved between two samples, or null when
 * the run describes one single build. Kept as a named function because the
 * claim "this report describes one build" is only checkable if the rule that
 * decides it is itself checkable.
 */
export function buildDrift(before, after) {
  if (!before || !after) return 'the fingerprint was never taken';
  const changed = [];
  for (const key of ['plugin_source', 'lib_index', 'lib_client', 'acceptance_source', 'case_file']) {
    if (JSON.stringify(before[key] ?? null) !== JSON.stringify(after[key] ?? null)) changed.push(key);
  }
  const beforePatches = JSON.stringify(before.patches ?? []);
  if (beforePatches !== JSON.stringify(after.patches ?? [])) changed.push('patches');
  return changed.length ? changed.join(', ') : null;
}

export function computeBuildHashes(caseDef, patches) {
  return {
    plugin_source: hashTree(join(PROJECT_ROOT, 'adapter/src')),
    lib_index: hashFile(join(PROJECT_ROOT, 'lib/index.js')),
    lib_client: hashFile(join(PROJECT_ROOT, 'lib/client.js')),
    // The acceptance code is part of the experiment: a checker or a scenario
    // that changed mid-run would make the report describe two different tests.
    acceptance_source: hashTree(join(PROJECT_ROOT, 'acceptance')),
    case_file: caseDef.id ? hashFile(join(CASES_DIR, `${caseDef.id}.json`)) : null,
    patches: (patches ?? []).map(path => ({ path, digest: hashFile(path) })),
  };
}

function loadCase(name) {
  if (!name) throw new Error('--case is required');
  const path = join(CASES_DIR, `${name}.json`);
  if (!existsSync(path)) throw new Error(`unknown case ${JSON.stringify(name)}; expected a file at ${path}`);
  return { id: name, ...JSON.parse(readFileSync(path, 'utf8')) };
}

async function runOnce({ args, caseDef, mode, runId }) {
  const layout = createRunLayout(ARTIFACTS_ROOT, runId);
  const profile = `dsh-flow-${runId}`.replace(/[^A-Za-z0-9._-]/g, '-');
  if (args.mock) {
    // A mock run fixes the model *input*. An extra model overlay or a
    // budget/turn multiplier would make the verdict describe something other
    // than the frozen fixture the case declares.
    for (const forbidden of ['profile-patch', 'budget-scale', 'max-role-turns']) {
      if (args[forbidden] !== undefined) {
        throw new Error(`--mock refuses --${forbidden}: the mock suite runs the frozen fixture, not a scaled experiment`);
      }
    }
  }
  const mock = args.mock ? await startMockModel({ modelId: MOCK_MODEL_ID }) : null;
  const modelRoute = mock
    ? { baseURL: mock.baseURL, model: MOCK_MODEL_ID, provider: MOCK_PROVIDER }
    : modelRouteFromEnv();
  const patches = (caseDef.patches ?? [caseDef.patch ?? 'examples/cluster.patch.yml'])
    .concat(args['profile-patch'] ? [args['profile-patch']] : [])
    .map(entry => resolve(PROJECT_ROOT, entry));
  if (mock) {
    const overlay = join(layout.root, 'mock-model.patch.yml');
    writeFileSync(overlay, mockPatchText(mock.baseURL));
    patches.push(overlay);
  }
  const patch = patches[0];
  const caseEnv = validateCaseEnv(caseDef);
  // The build fingerprint is taken before anything runs and re-checked at the
  // end: a report whose code changed mid-run describes no single build.
  const budgetScale = args['budget-scale'] ?? 1;
  const settleTimeoutMs = args['timeout-ms'] ?? (caseDef.timeout_ms ?? 3_600_000) * budgetScale;
  if (!Number.isSafeInteger(settleTimeoutMs) || settleTimeoutMs < 1) throw new Error('settle timeout must be a positive safe integer');
  const buildHashesAtStart = computeBuildHashes(caseDef, patches);

  const started = Date.now();
  const report = {
    run_id: runId,
    case: caseDef.id,
    mode,
    title: caseDef.title,
    started_at: new Date(started).toISOString(),
    validation_mode: mock ? 'mock-api' : 'live-model',
    model_route: modelRoute,
    patch,
    patches,
    profile,
    paths: { ...layout },
    build_hashes: buildHashesAtStart,
    input_hashes: {},
    mechanism_pass: 'UNKNOWN',
    scenario_status: 'UNKNOWN',
    quality_checks: [],
    failure_class: null,
    notes: [],
    ...(budgetScale !== 1 || args['max-role-turns'] !== undefined
      ? { experiment: { budget_scale: budgetScale, max_role_turns: args['max-role-turns'] ?? null, settle_timeout_ms: settleTimeoutMs } }
      : {}),
  };

  const workspace = layout.workspace;
  const preparation = prepareWorkspace(caseDef, workspace, layout, mode);
  report.preparation = preparation;
  // Two different fingerprints, named for what they fingerprint: `input_hashes`
  // is the data the run consumed, `build_hashes` is the code that ran.
  report.input_hashes = preparation.source_hashes ?? {};

  const checksModule = await loadChecksModule(caseDef.id);
  const baselineArgs = { caseDef, mode, layout, workspace, report, args };
  if (checksModule?.before) report.baseline = await checksModule.before(baselineArgs);

  ensureProfile(layout.home, profile, { bundles: WEB_PROFILE_BUNDLES });
  // Chromium's SingletonSocket uses a Unix-domain pathname with a hard
  // length cap. Keep the actual scratch files under this isolated run, but
  // expose a short, per-run TMPDIR alias to the browser-capable host.
  const browserTmpAlias = caseDef.capabilities?.includes('browser')
    ? join(tmpdir(), `dsh-${randomUUID().slice(0, 12)}`) : null;
  if (browserTmpAlias) {
    symlinkSync(layout.tmp, browserTmpAlias, 'dir');
    report.notes.push(`browser TMPDIR ${browserTmpAlias} -> ${layout.tmp}`);
  }
  const env = buildHostEnv({
    home: layout.home, tmpdir: browserTmpAlias ?? layout.tmp, dataDir: layout.data, workspace, modelRoute,
    modelApiKey: mock ? MOCK_API_KEY : process.env.FLOW_MODEL_API_KEY,
    extra: caseEnv,
  });
  if (mock) {
    report.mock = { scenario: `mock:${caseDef.id}`, base_url: mock.baseURL, model: MOCK_MODEL_ID };
  }

  let host = new DshHost({
    profile,
    patches,
    cwd: workspace,
    env,
    logPath: join(layout.logs, 'host.log'),
  });

  const events = [];
  let snapshot = null;
  let single = null;
  let failure = null;
  try {
    await host.start();
    report.notes.push(`host booted (pid ${host.child.pid}) with profile ${profile}`);
    try {
      await host.waitForWebUrl(120_000);
      report.web_url = host.webUrl;
    } catch (error) {
      report.notes.push(`web URL not observed: ${error.message}`);
    }
    // The host's own web URL is known before the cluster starts, so a case can
    // name it: the browser case drives the host's authenticated page instead of
    // depending on the public internet.
    const spec = buildSpec(caseDef, workspace, mode, runId, args['dataset-limit'], { webUrl: report.web_url ?? null });
    // A concurrency ladder changes exactly one knob at a time.
    if (args['max-llm-concurrency'] !== undefined) {
      spec.limits = { ...spec.limits, max_llm_concurrency: Number(args['max-llm-concurrency']) };
      spec.budget = { ...spec.budget, max_active_agents: spec.budget.max_active_agents ?? spec.limits.max_active_agents };
    }
    if (args['max-active-agents'] !== undefined) {
      spec.limits = { ...spec.limits, max_active_agents: Number(args['max-active-agents']) };
    }
    assertTierBudget(spec);
    delete spec.generated_tier;
    if (budgetScale !== 1) {
      // The case remains an immutable baseline. The effective budget and this
      // override are both written into the report under a new run id; identity
      // and concurrency ceilings stay unchanged.
      for (const dimension of ['tokens', 'model_requests', 'tool_calls', 'wall_time_ms']) {
        const scaled = spec.budget[dimension] * budgetScale;
        if (!Number.isSafeInteger(scaled)) throw new Error(`scaled ${dimension} is not a safe integer`);
        spec.budget[dimension] = scaled;
      }
    }
    if (args['max-role-turns'] !== undefined) spec.limits.max_role_turns = args['max-role-turns'];
    // Every fixture id is run-scoped before anything is written, so a collision
    // is a clear pre-flight error instead of a half-populated database.
    const namespaced = namespaceFixtures(spec, runId);
    report.fixture_id_map = namespaced.map;
    report.spec = namespaced.spec;
    if (mock) {
      // Bound after namespacing and before `start`: the scenario names the same
      // transactions the case does, and a request that arrives before a script
      // exists is a fixture error rather than a default answer.
      const scenario = buildScenario({
        caseId: caseDef.id, layout, workspace, fixtureIds: namespaced.map, runId, limits: namespaced.spec.limits,
      });
      mock.setScenario(scenario);
      report.mock.scenario = scenario.name;
    }

    if (mode === 'single') {
      const singleTurn = await host.request('single', undefined, {
        objective: namespaced.spec.objective,
        workspace,
        capabilities: namespaced.spec.capabilities,
        budget: namespaced.spec.budget,
        initial_transactions: namespaced.spec.initial_transactions,
        acceptance_criteria: namespaced.spec.acceptance_criteria,
      }, settleTimeoutMs);
      single = singleTurn;
      report.single = singleTurn;
      // The control run is a cluster of its own: report it as such so the
      // ledger and the mechanism gate are computed from the same source.
      report.cluster_id = singleTurn.cluster_id;
    } else {
      const created = await host.request('start', undefined, namespaced.spec, 120_000);
      report.cluster_id = created.cluster.id;
      if (mock && caseDef.scale_fixture?.concurrency_probe) {
        // Hold exactly `max_llm_concurrency` Worker requests open at once and
        // watch the wire: while they are held, a request beyond the ceiling
        // would have to arrive here. Nothing else can prove the ceiling is
        // enforced rather than merely reported.
        const ceiling = Number(namespaced.spec.limits.max_llm_concurrency ?? 2);
        await mock.waitUntilHeld(ceiling, { barrier: 'scale-concurrency', timeoutMs: 120_000 });
        const beforeProbe = mock.requests.length;
        const probeWindowMs = Number(caseDef.scale_fixture.concurrency_probe_window_ms ?? 3000);
        await new Promise(resolvePromise => setTimeout(resolvePromise, probeWindowMs));
        report.concurrency_probe = {
          ceiling,
          held_simultaneously: mock.heldCount('scale-concurrency'),
          requests_while_held: mock.requests.length - beforeProbe,
          window_ms: probeWindowMs,
        };
        mock.release('scale-concurrency');
      }
      if (caseDef.live_first && checksModule?.live) {
        try {
          report.live_checks = await checksModule.live({ caseDef, mode, layout, workspace, report, host, env, args, mock });
        } catch (error) {
          report.live_checks = { checks: [], error: String(error?.message ?? error) };
          report.notes.push(`live checks failed: ${error?.message ?? error}`);
        }
      }
      if (caseDef.recovery?.require_restart) {
        const outcome = await restartMidFlight({
          host, caseDef, layout, report, args, workspace, profile, patches, env, mock,
        });
        host = outcome.host;
        report.restart = outcome.facts;
      }
      await host.request('settle', created.cluster.id, {
        timeout_ms: settleTimeoutMs,
        poll_ms: 400,
      }, settleTimeoutMs + 120_000);
      snapshot = await host.request('read', created.cluster.id, { include_events: false, limit: 500 }, 120_000);
      events.push(...await drainEvents(host, created.cluster.id));
      report.report = await host.request('report', created.cluster.id, {}, 120_000);
    }
    // Checks that need the live host (the panel, the authenticated route) run
    // before shutdown; everything else runs afterwards from durable state.
    if (!caseDef.live_first && checksModule?.live) {
      try {
        report.live_checks = await checksModule.live({ caseDef, mode, layout, workspace, report, host, env, args, snapshot, events, mock });
      } catch (error) {
        report.live_checks = { checks: [], error: String(error?.message ?? error) };
        report.notes.push(`live checks failed: ${error?.message ?? error}`);
      }
    }
  } catch (error) {
    failure = { message: String(error?.message ?? error), stack: String(error?.stack ?? '') };
    report.failure_class = 'MECHANISM';
  } finally {
    if (!args['keep-host']) {
      const stopped = await host.stop();
      report.host_exit = stopped;
    }
    if (browserTmpAlias && !args['keep-host']) unlinkSync(browserTmpAlias);
    if (mock && !args['keep-host']) {
      try {
        report.mock_fixture = { ok: true, ...mock.assertComplete() };
      } catch (error) {
        // A scenario that could not recognise a request, held one that never
        // released, or saw a protocol drift is an *acceptance facility* defect:
        // it fails the run rather than being reported as a plugin outcome.
        report.mock_fixture = { ok: false, problem: String(error?.message ?? error), errors: [...mock.errors] };
      }
      report.mock_requests = summarizeMockRequests(mock);
      report.mock_concurrency = {
        peak_concurrent_requests: mock.peakConcurrency(),
        requests: mock.requests.length,
      };
      writeFileSync(join(layout.root, 'mock-requests.json'), `${JSON.stringify(mock.requests.map(entry => ({
        seq: entry.seq, at: entry.at, model: entry.model, kind: entry.kind, role: entry.role,
        node_id: entry.node_id, agent_id: entry.agent_id, transaction_id: entry.transaction_id,
        tools: entry.tools, authorized: entry.authorized, request_shape: entry.request_shape,
        digest_source: entry.classified?.digest_source ?? null,
        barrier: entry.barrier, held: entry.held, response: entry.response ?? null,
        opened_at: entry.opened_at ?? null, closed_at: entry.closed_at ?? null,
        prompt_preview: String(entry.classified?.userText ?? '').slice(0, 1200),
        last_tool_name: entry.classified?.lastToolName ?? null,
        last_tool_result: entry.classified?.lastToolResult === null || entry.classified?.lastToolResult === undefined
          ? null : String(entry.classified.lastToolResult).slice(0, 600),
        // An unrecognised request is the one case where the full message shape
        // is the evidence needed to fix the fixture; it is never the normal
        // record, which would store the whole session on every run.
        ...(entry.kind === 'unknown' || entry.diagnostic ? {
          diagnostics: (entry.body?.messages ?? []).map(message => ({
            role: message.role,
            tool_calls: Array.isArray(message.tool_calls) ? message.tool_calls.map(call => call.function?.name) : undefined,
            text: (typeof message.content === 'string' ? message.content
              : (message.content ?? []).map(part => part?.text ?? '').join('\n')).slice(0, 2000),
          })),
        } : {}),
      })), null, 2)}\n`);
      await mock.close();
    }
  }

  report.failure = failure;

  const ledger = readStoneLedger(layout, report.cluster_id ?? null);
  report.ledger = ledger;

  // The clock and the structured limit evidence are measured *before* the case's
  // checks, because those checks derive their own verdict from them.
  measureRun(report, {
    startedAt: started,
    budget: report.spec?.budget ?? {},
    usage: ledger.usage ?? {},
    clusterReason: ledger.blocked_reason ?? null,
    refusals: ledger.structured_budget_refusals ?? [],
    buildHashes: computeBuildHashes(caseDef, patches),
  });
  const checkResult = await runChecks({ caseDef, mode, layout, workspace, report, single, snapshot, events, host, env, args });
  report.quality_checks = checkResult.checks;
  report.scenario_status = checkResult.scenario_status;
  // A fixture that could not answer a request, or held one that never released,
  // is an acceptance-facility failure. It is never allowed to pass as a plugin
  // outcome, and it is never relabelled as a model-quality result.
  if (report.mock_fixture && report.mock_fixture.ok === false) {
    report.scenario_status = 'FAILED';
    report.failure_class = 'FIXTURE';
  }
  // Classification is finalised before the mechanism verdict is computed, so a
  // check-level MECHANISM failure can never be relabelled by the budget branch.
  // Only a class the checks *derived* is carried here: stamping MODEL_OUTPUT on
  // every unclassified failure before the limit facts were consulted labelled a
  // budget-limited run as a model failure (measured: 16 structured refusals and a
  // `MODEL_OUTPUT` class on the same report).
  if (report.failure_class === null && report.scenario_status === 'FAILED' && checkResult.failure_class) {
    report.failure_class = checkResult.failure_class;
  }
  // The wall clock is *measured here*, before it is classified: passing
  // `report.wall_time_ms` while it is still unset made every wall-time verdict a
  // comparison against zero.
  report.finished_at = new Date().toISOString();
  report.wall_time_ms = Date.now() - started;
  // The same measurement again, now that the checks may have set a class: the
  // measurement is idempotent, and the *class* is what the checks may not
  // overwrite.
  // An explicit budget or wall-time exhaustion is its own verdict: the
  // scenario did not fail because the model was wrong, it stopped because the
  // fixture's own limit was reached.
  const classification = classifyOutcome({
    failureClass: report.failure_class, scenarioStatus: report.scenario_status,
    budget: report.spec?.budget ?? {}, usage: ledger.usage ?? {}, wallTimeMs: report.wall_time_ms,
    clusterReason: ledger.blocked_reason ?? null,
    // Only a *structured* refusal (a persisted budget-refused record with its
    // scope and dimension) is evidence that a limit was really reached. Free
    // text, a near-ceiling ratio or a tool refusal never is.
    refusals: ledger.structured_budget_refusals ?? [],
  });
  report.failure_class = classification.failure_class;
  report.limit_reached = classification.limit_reached;
  report.mechanism_pass = mechanismVerdict(report, ledger);
  if (checkResult.scale_validation) {
    // The plan reads this flag from the report: a tier that did not really run
    // its workers must never be summarised as a verified scale number.
    report.scale_validation = checkResult.scale_validation;
    report.scale_metrics = checkResult.metrics ?? null;
    report.measured_per_file = checkResult.measured_per_file ?? null;
  }
  // A report whose build changed while it ran describes no single build.
  const buildHashesAtEnd = computeBuildHashes(caseDef, patches);
  const drift = buildDrift(report.build_hashes, buildHashesAtEnd);
  report.build_drift = drift;
  if (drift) {
    report.not_comparable = true;
    report.notes.push(`build_hashes changed during the run (${drift}); the report does not describe one build`);
  }

  writeFileSync(join(layout.root, 'report.json'), `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(join(layout.root, 'events.jsonl'), `${events.map(event => JSON.stringify(event)).join('\n')}\n`);
  writeFileSync(join(layout.root, 'usage.json'), `${JSON.stringify(ledger.usage ?? null, null, 2)}\n`);
  writeFileSync(join(layout.root, 'checks.json'), `${JSON.stringify(checkResult, null, 2)}\n`);
  writeFileSync(join(layout.root, 'sessions.json'), `${JSON.stringify(listSessions(layout), null, 2)}\n`);
  if (snapshot) writeFileSync(join(layout.root, 'state.json'), `${JSON.stringify(snapshot, null, 2)}\n`);

  console.log(`[${runId}] mode=${mode} scenario=${report.scenario_status} mechanism=${report.mechanism_pass} reports=${layout.root}`);
  return {
    run_id: runId,
    mode,
    scenario_status: report.scenario_status,
    mechanism_pass: report.mechanism_pass,
    failure_class: report.failure_class,
    wall_time_ms: report.wall_time_ms,
    cluster_id: report.cluster_id ?? null,
    report: join(layout.root, 'report.json'),
  };
}

/** Poll the durable event stream by cursor until the crash trigger or deadline. */
export async function waitForKillEvent(host, clusterId, killOn, delay, {
  now = Date.now,
  sleep = ms => new Promise(resolvePromise => setTimeout(resolvePromise, ms)),
} = {}) {
  const started = now();
  const deadline = started + delay;
  let since = 0;
  let seen = 0;
  let observedSeq = null;
  let pollError = null;
  let polls = 0;
  while (now() < deadline) {
    polls += 1;
    try {
      const page = await host.request('events', clusterId, { since, limit: 500 }, 30_000);
      const events = page?.events ?? [];
      const matches = events.filter(event => event.type === killOn);
      if (matches.length) {
        seen = matches.length;
        observedSeq = matches[0].seq;
        break;
      }
      if (events.length) since = events[events.length - 1].seq;
      // A full page means there may be more durable history already waiting.
      // Catch up before sleeping so the trigger is not lost behind old events.
      if (events.length === 500) continue;
    } catch (error) {
      // A failed poll must not look like "the window never opened".
      pollError = pollError ?? error.message;
      if (polls > 4) break;
    }
    await sleep(250);
  }
  const trigger = {
    event: killOn, observed: seen, observed_seq: observedSeq, polls, poll_error: pollError,
    cluster_id: clusterId ?? null, observed_at_ms: now() - started,
  };
  if (!seen) {
    trigger.note = pollError
      ? `polling failed (${pollError}); killed on the clock instead`
      : 'the trigger event did not occur before the deadline; killed on the clock instead';
  }
  return trigger;
}

/**
 * Kill the test host mid-flight and restart it against the same DSH_HOME and
 * data directory, capturing the durable facts on both sides of the crash.
 */
async function restartMidFlight({ host, caseDef, layout, report, args, workspace, profile, patches, env, mock = null }) {
  const delay = Number(caseDef.recovery?.kill_after_ms ?? 45_000);
  // A kill-on-event trigger lands the crash *inside* a named window instead of
  // at an arbitrary wall-clock moment. `delivery-flushed` is the one boundary a
  // poll of `messages-injected` cannot reach: the plugin records it after the
  // session is durable and before the delivery is acked.
  const killOn = caseDef.recovery?.kill_on_event ?? args['kill-on-event'] ?? null;
  // A kill-on-hold trigger is stronger than either: the crash lands while a
  // *named identity is holding a live model request*, proven by the fixture
  // that served it rather than inferred from an event poll.
  const killOnHold = caseDef.recovery?.kill_on_hold ?? args['kill-on-hold'] ?? null;
  const before = readStoneLedger(layout, report.cluster_id ?? null);
  if (killOnHold) {
    if (!mock) throw new Error(`case ${caseDef.id} requires --mock for its kill-on-hold trigger`);
    const held = await mock.waitForRequest(entry => entry.held && entry.barrier === killOnHold, { timeoutMs: delay });
    report.kill_trigger = {
      event: 'hold', barrier: killOnHold, observed: 1, observed_seq: null, polls: null,
      cluster_id: report.cluster_id ?? null, request_seq: held.seq, kind: held.kind,
      role: held.role, agent_id: held.agent_id, transaction_id: held.transaction_id,
      observed_at_ms: held.at,
    };
  } else if (killOn) {
    report.kill_trigger = await waitForKillEvent(host, report.cluster_id, killOn, delay);
  }
  const killAtMs = Date.now();
  const stopped = await host.stop({ signal: 'SIGKILL', graceMs: 2000 });
  const atCrash = readStoneLedger(layout, report.cluster_id ?? null);
  // The exact receipts that were dispatched and never settled at the crash: the
  // expected number of UNKNOWN results is this set, not an arbitrary allowance.
  const inFlight = (atCrash.usage_rows ?? []).filter(row => row.settled === null && row.created <= killAtMs);
  await new Promise(resolvePromise => setTimeout(resolvePromise, Number(caseDef.recovery?.restart_delay_ms ?? 2000)));
  const restarted = new DshHost({ profile, patches, cwd: workspace, env, logPath: join(layout.logs, 'host-restart.log') });
  await restarted.start();
  return {
    host: restarted,
    facts: {
      kill_after_ms: delay,
      // The wall clock and the event cursor at the moment of the kill: the
      // crash window is attributed against these, never assumed.
      kill_at_ms: killAtMs,
      event_seq_at_kill: atCrash.event_seq ?? null,
      kill_trigger: report.kill_trigger ?? null,
      exit: stopped,
      usage_at_crash: atCrash.usage,
      usage_before_kill: before.usage,
      accepted_at_crash: atCrash.transactions_by_status,
      uncertain_effects_at_crash: atCrash.effects,
      leases_at_crash: atCrash.lease_rows,
      // Receipts dispatched but unsettled, and the transactions that were not
      // yet terminal: the crash's own account of what it interrupted.
      receipts_in_flight_at_crash: inFlight.map(row => ({
        request_id: row.request_id, agent_id: row.agent_id, role: row.role, kind: row.kind, created: row.created,
      })),
      transactions_open_at_crash: (atCrash.transactions_detail ?? []).filter(row => row.status !== 'ACCEPTED'),
      restarted: true,
    },
  };
}

async function loadChecksModule(caseId) {
  const path = join(CHECKS_DIR, `${caseId}.mjs`);
  if (!existsSync(path)) return null;
  return import(path);
}

async function drainEvents(host, clusterId) {
  const out = [];
  let since = 0;
  for (;;) {
    const page = await host.request('events', clusterId, { since, limit: 500 }, 120_000);
    if (!page.events?.length) break;
    out.push(...page.events);
    since = page.events[page.events.length - 1].seq;
    if (page.events.length < 500) break;
  }
  return out;
}

function buildSpec(caseDef, workspace, mode, runId, datasetLimit, extra = {}) {
  const limits = { ...(caseDef.limits ?? {}), ...(MODE_LIMITS[mode] ?? {}) };
  const budget = { ...(caseDef.budget ?? {}) };
  if (budget.wall_time_ms === undefined) budget.wall_time_ms = caseDef.timeout_ms ?? 3_600_000;
  const generated = datasetTransactions(caseDef, workspace, datasetLimit);
  if (generated.length) {
    // A scale fixture is the control-plane baseline: one worker per file, no
    // model-authored decomposition, so throughput is not confused with
    // planning ability.
    // The approved V6 tier budget is a function of N, not a ceiling: keeping the
    // case's 1024-tier numbers would let a 16-file canary spend 64x its tier and
    // would not test the limits the plan actually approved.
    budget.tokens = 65536 * generated.length;
    budget.model_requests = 12 * generated.length;
    budget.tool_calls = 16 * generated.length;
    limits.max_agents = Math.max(limits.max_agents ?? 0, generated.length + 32);
    limits.max_role_turns = Math.max(limits.max_role_turns ?? 0, Math.ceil(generated.length / 8) + 16);
    // One Worker may send at most `worker_model_requests` model requests (V6);
    // compaction is accounted separately and does not consume this allowance.
    limits.worker_model_requests = caseDef.scale_fixture?.worker_model_requests ?? 2;
    limits.worker_max_tokens = caseDef.scale_fixture?.worker_max_tokens ?? 512;
  }
  const values = { workspace, runId, webUrl: extra.webUrl ?? '' };
  return {
    objective: substitute(caseDef.objective, values),
    workspace,
    capabilities: caseDef.capabilities ?? ['fs_read'],
    limits,
    budget,
    ...(generated.length ? { generated_tier: true } : {}),
    ...(generated.length
      ? { initial_transactions: generated }
      : caseDef.initial_transactions
        ? { initial_transactions: caseDef.initial_transactions.map(entry => substituteObject(entry, values)) }
        : {}),
    ...(caseDef.acceptance_criteria ? { acceptance_criteria: caseDef.acceptance_criteria.map(text => substitute(text, values)) } : {}),
    ...(caseDef.delegation ? { delegation: caseDef.delegation.map(entry => substituteObject(entry, values)) } : {}),
    ...(caseDef.message_fixture ? { message_fixture: caseDef.message_fixture.map(entry => substituteObject(entry, values)) } : {}),
    ...(mode === 'flat' ? { notes: 'flat control: root roles plus direct workers, no nested management' } : {}),
  };
}

/** One transaction per dataset entry, capped by the requested ladder step. */
function datasetTransactions(caseDef, workspace, datasetLimit) {
  if (!caseDef.dataset) return [];
  const path = join(workspace, caseDef.dataset.file ?? 'dataset.json');
  if (!existsSync(path)) return [];
  const dataset = JSON.parse(readFileSync(path, 'utf8'));
  const limit = datasetLimit ?? caseDef.scale_fixture?.workers ?? dataset.count ?? 0;
  return dataset.entries.slice(0, limit).map(entry => ({
    id: `scale-${entry.path.replace(/[^A-Za-z0-9._-]/g, '_')}`,
    objective: [
      `Read the file ${entry.workspace_path} (relative to the workspace) with the read tool.`,
      'Submit a result object with exactly these fields:',
      `{"file": "${entry.workspace_path}", "symbol": "<one real exported symbol or top-level declaration, copied exactly as it appears>", "line": <line number you saw it on>, "responsibility": "<one sentence>"}`,
      'If the file really has no identifiable symbol, submit {"file": "...", "symbol": "unknown", "reason": "<why>"}.',
    ].join(' '),
    expected_output: 'A result naming a symbol and a line number, or an explicit "unknown".',
    acceptance_criteria: [
      'The result names a symbol that appears in the file, or states unknown with a reason',
      'The result quotes the line number it saw',
    ],
    inputs: { path: entry.path, file: entry.workspace_path, hash: entry.hash },
    priority: 0,
  }));
}

/**
 * Give every fixture transaction id a run-scoped namespace before `start`.
 *
 * The fixture files use stable ids (`rec-deep`, `panel-tx`) so a case can be
 * read and diffed; two runs must not collide on them. Mapping the ids here —
 * and validating that every reference still resolves — turns a mid-`start`
 * SQLite `UNIQUE constraint failed` into a clear error before anything is
 * written. Ids a case already namespaced by template are left alone.
 */
export function namespaceFixtures(spec, runId) {
  const transactions = spec.initial_transactions ?? [];
  const ids = new Set(transactions.map(entry => entry.id).filter(id => typeof id === 'string' && id));
  const map = {};
  for (const id of ids) map[id] = id.startsWith(`${runId}-`) ? id : `${runId}-${id}`;
  const mapped = value => (typeof value === 'string' && ids.has(value) ? map[value] : value);
  const mappedList = value => (Array.isArray(value) ? value.map(mapped) : value);
  const namespaced = {
    ...spec,
    ...(spec.initial_transactions
      ? {
        initial_transactions: spec.initial_transactions.map(entry => ({
          ...entry,
          id: mapped(entry.id),
          parent_transaction_id: mapped(entry.parent_transaction_id),
          needs: mappedList(entry.needs),
          depends_on: mappedList(entry.depends_on),
        })),
      }
      : {}),
    ...(spec.message_fixture
      ? { message_fixture: spec.message_fixture.map(entry => ({ ...entry, from: mapped(entry.from), to: mapped(entry.to) })) }
      : {}),
  };
  const finalIds = [];
  for (const entry of namespaced.initial_transactions ?? []) {
    if (typeof entry.id !== 'string' || !entry.id) throw new Error(`fixture transaction without an id: ${JSON.stringify(entry.objective ?? null)}`);
    finalIds.push(entry.id);
  }
  const duplicates = finalIds.filter((id, index) => finalIds.indexOf(id) !== index);
  if (duplicates.length) throw new Error(`fixture transaction ids are not unique after namespacing: ${[...new Set(duplicates)].join(', ')}`);
  const known = new Set(finalIds);
  for (const entry of namespaced.initial_transactions ?? []) {
    const references = [
      entry.parent_transaction_id,
      ...(Array.isArray(entry.needs) ? entry.needs : []),
      ...(Array.isArray(entry.depends_on) ? entry.depends_on : []),
    ].filter(value => typeof value === 'string' && value);
    for (const reference of references) {
      if (!known.has(reference)) throw new Error(`fixture transaction ${entry.id} references unknown transaction ${reference}`);
    }
  }
  for (const fixture of namespaced.message_fixture ?? []) {
    for (const endpoint of ['from', 'to']) {
      if (!known.has(fixture[endpoint])) {
        throw new Error(`message fixture ${endpoint} references unknown transaction ${String(fixture[endpoint])}`);
      }
    }
  }
  return { spec: namespaced, map, ids: finalIds };
}

/**
 * The tier's denominator has exactly one source: the fixture the runner
 * generated. A run whose declared budget is not the function of N it claims is
 * not the tier it reports, so this throws *before* `start` writes anything.
 */
export function assertTierBudget(spec) {
  if (spec.generated_tier !== true) return;
  const planned = (spec.initial_transactions ?? []).length;
  const budget = spec.budget ?? {};
  const expected = { tokens: 65536 * planned, model_requests: 12 * planned, tool_calls: 16 * planned };
  for (const [key, value] of Object.entries(expected)) {
    if (budget[key] !== value) throw new Error(`tier budget mismatch: ${key} is ${budget[key]}, expected ${value} for ${planned} planned transactions`);
  }
}

const substitute = (text, values) => typeof text === 'string'
  ? text.replace(/\{\{(\w+)\}\}/g, (_, key) => (values[key] === undefined ? '' : String(values[key])))
  : text;
const substituteObject = (value, values) => JSON.parse(JSON.stringify(value), (key, item) => (typeof item === 'string' ? substitute(item, values) : item));

function prepareWorkspace(caseDef, workspace, layout, mode) {
  const prep = { kind: caseDef.workspace?.kind ?? 'empty', details: [] };
  const config = caseDef.workspace ?? {};
  if (config.kind === 'generated-corpus') {
    // The scale ladder's corpus is generated into the *run* directory from a
    // fixed recipe: every file, its exported symbol, its line and its content
    // hash are known before the run starts, so "this Worker really read this
    // file and quoted this declaration" is a comparison, not a judgement.
    rmSync(workspace, { recursive: true, force: true });
    mkdirSync(workspace, { recursive: true });
    const generated = generateCorpus(workspace, config);
    prep.details.push(`generated ${generated.count} fixture files in ${generated.dir}`);
    prep.generated_corpus = { dir: generated.dir, count: generated.count, manifest: generated.manifestPath };
  } else if (config.kind === 'seed') {
    const seed = resolve(PROJECT_ROOT, config.seed);
    rmSync(workspace, { recursive: true, force: true });
    const result = spawnSync('cp', ['-a', `${seed}/.`, workspace], { encoding: 'utf8' });
    if (result.status !== 0) throw new Error(`seed copy failed: ${result.stderr}`);
    prep.details.push(`copied seed ${seed}`);
  } else if (config.kind === 'copy-repo') {
    const source = resolve(config.source);
    rmSync(workspace, { recursive: true, force: true });
    mkdirSync(workspace, { recursive: true });
    const base = ['-a'];
    for (const pattern of config.exclude ?? []) base.push(`--exclude=${pattern}`);
    const attempt = extra => spawnSync('rsync', [...base, ...extra, `${source}/.`, workspace], { encoding: 'utf8', maxBuffer: 1 << 30 });
    // Reflink is a speed optimisation, not a requirement: this rsync build
    // rejects the option, so fall back to a plain copy and record which ran.
    let result = attempt(['--reflink=auto']);
    let mode = 'reflink';
    if (result.status !== 0 && /reflink/.test(String(result.stderr))) {
      rmSync(workspace, { recursive: true, force: true });
      mkdirSync(workspace, { recursive: true });
      result = attempt([]);
      mode = 'plain';
    }
    if (result.status !== 0) throw new Error(`workspace copy failed (${result.status}): ${result.stderr}`);
    prep.details.push(`rsync (${mode}) copy of ${source}`);
    const exclude = config.hashExclude ?? ['node_modules', '.git', '.artifacts'];
    const before = buildManifest(source, exclude);
    writeFileSync(join(layout.root, 'source-manifest-before.json'), `${JSON.stringify(before, null, 2)}\n`);
    writeFileSync(join(layout.root, 'source-manifest-meta.json'), `${JSON.stringify({ exclude, taken_at: new Date().toISOString() })}\n`);
    prep.source_hashes = { digest: before.digest, files: before.files, excluded: exclude };
    // A copy that is not isolated must abort here, before any baseline or
    // build command can mutate the workspace.
    prep.copy_integrity = enforceCopyIsolation(source, workspace, {
      allowedRoots: config.allowedLinkRoots ?? [
        join(source, 'node_modules'),
        '/home/leo/.cache',
        '/home/leo/.local/share/pnpm',
        '/usr',
        '/opt',
        '/tmp',
      ],
    });
  } else {
    mkdirSync(workspace, { recursive: true });
  }
  if (config.prepare === 'npm-ci') {
    const result = spawnSync('npm', ['ci', '--ignore-scripts'], { cwd: workspace, encoding: 'utf8', maxBuffer: 1 << 28 });
    prep.npm_ci = { status: result.status, stderr: (result.stderr ?? '').slice(-2000) };
    if (result.status !== 0) throw new Error(`npm ci failed in the case workspace: ${result.stderr}`);
    prep.details.push('npm ci --ignore-scripts');
  }
  if (caseDef.dataset) {
    prep.dataset = buildDataset(caseDef.dataset, workspace);
  }
  return prep;
}

/**
 * Generate the scale ladder's fixed corpus.
 *
 * Deterministic by construction: the file set, each file's exported symbol, the
 * line that declaration sits on and the file's content are all produced here,
 * so the expected answer for every tier transaction exists before any model is
 * asked. The manifest is written beside the corpus, not inside it, so it can
 * never be mistaken for a corpus file.
 */
function generateCorpus(workspace, config) {
  const dir = join(workspace, config.dir ?? 'corpus-src');
  const count = config.count ?? 64;
  const manifest = [];
  mkdirSync(dir, { recursive: true });
  for (let index = 0; index < count; index += 1) {
    const folder = config.groups ? `group-${String(index % config.groups).padStart(2, '0')}` : null;
    const name = `module-${String(index).padStart(3, '0')}.js`;
    const relative = folder ? `${folder}/${name}` : name;
    const symbol = `fixtureSymbol${String(index).padStart(3, '0')}`;
    const lines = [
      `// scale fixture module ${index}: generated deterministically for the acceptance run`,
      '// the declaration on the next line is the only symbol a Worker has to find',
      `export function ${symbol}(input) {`,
      `  return input + ${index};`,
      '}',
      '',
    ];
    mkdirSync(dirname(join(dir, relative)), { recursive: true });
    writeFileSync(join(dir, relative), lines.join('\n'));
    manifest.push({
      path: relative, symbol, line: 3,
      sha256: `sha256:${createHash('sha256').update(lines.join('\n')).digest('hex')}`,
    });
  }
  const manifestPath = join(workspace, config.manifest ?? 'corpus-manifest.json');
  writeFileSync(manifestPath, `${JSON.stringify({ dir: config.dir ?? 'corpus-src', count, entries: manifest }, null, 2)}\n`);
  return { dir, count, manifest, manifestPath };
}

/**
 * Build the scale corpus: the selected source files are *copied into the run's
 * workspace* so every worker reads a real file through the host read tool, and
 * the dataset records each file's sha256 and a bounded excerpt.
 */
function buildDataset(config, workspace) {
  const datasetPath = join(workspace, config.file ?? 'dataset.json');
  const root = config.root ? resolve(substitute(config.root, { workspace })) : join(workspace, config.source ?? 'corpus-src');
  const corpus = join(workspace, config.corpus ?? 'corpus');
  const listed = listFiles(root, config.limit ?? 1024, config.extensions ?? ['.ts', '.tsx', '.js', '.mjs', '.cjs', '.md', '.json', '.py', '.java', '.go', '.rs']);
  const entries = listed.map(file => {
    const relative = file.slice(root.length + 1);
    const target = join(corpus, relative);
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(file, target);
    const text = readFileSync(target, 'utf8');
    return {
      path: relative,
      workspace_path: join(config.corpus ?? 'corpus', relative),
      hash: hashFile(target),
      excerpt: text.slice(0, config.excerpt_bytes ?? 4096),
    };
  });
  writeFileSync(datasetPath, `${JSON.stringify({ root, corpus: config.corpus ?? 'corpus', count: entries.length, entries }, null, 2)}\n`);
  return { path: datasetPath, corpus, count: entries.length };
}

function listFiles(root, limit, extensions) {
  const out = [];
  const queue = [root];
  const skip = new Set(['.git', 'node_modules', 'dist', 'lib', 'coverage', '.artifacts']);
  while (queue.length && out.length < limit) {
    const current = queue.shift();
    let entries;
    try {
      entries = readdirSync(current, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (out.length >= limit) break;
      if (entry.name.startsWith('.') && entry.name !== '.') continue;
      if (skip.has(entry.name)) continue;
      const full = join(current, entry.name);
      if (entry.isDirectory()) queue.push(full);
      else if (entry.isFile() && extensions.some(extension => entry.name.endsWith(extension))) out.push(full);
    }
  }
  return out.sort();
}

function simpleHash(text) {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return `fnv1a:${(hash >>> 0).toString(16)}`;
}

/**
 * Complete path→hash manifest of a tree, excluding only the directory names the
 * caller names. Exclusion is the only knob: a positive glob filter would hash
 * the wrong files.
 */
function buildManifest(root, exclude = []) {
  const entries = {};
  const skip = new Set(exclude);
  const walkDir = (dir, prefix) => {
    let listing;
    try {
      listing = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of listing) {
      if (skip.has(entry.name)) continue;
      const full = join(dir, entry.name);
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walkDir(full, relative);
      else if (entry.isFile()) {
        try {
          entries[relative] = createHash('sha1').update(readFileSync(full)).digest('hex');
        } catch {
          entries[relative] = 'unreadable';
        }
      } else if (entry.isSymbolicLink()) {
        entries[relative] = `symlink:${readlinkSync(full)}`;
      }
    }
  };
  walkDir(root, '');
  const names = Object.keys(entries).sort();
  const digest = createHash('sha1');
  for (const name of names) digest.update(`${name}\u0000${entries[name]}\n`);
  return { root, files: names.length, digest: digest.digest('hex'), entries };
}

/**
 * Isolation preflight for a copied workspace: no symlink may resolve back into
 * the original repository, and no regular file may share an inode with its
 * source (which would make the "copy" a hardlink).
 */
/**
 * Isolation gate for a copied workspace. It walks the *whole* copy (minus
 * `node_modules`, whose symlinks are the package manager's read-only store
 * links) and aborts on:
 *   - a symlink whose canonical target leaves the copy and the allowed
 *     read-only roots (in particular: resolving back into the source tree);
 *   - a regular file that shares `(dev, ino)` with its source counterpart,
 *     which would make the "copy" a hardlink.
 */
function enforceCopyIsolation(source, copy, { allowedRoots = [] } = {}) {
  const canonical = path => {
    try {
      return realpathSync(path);
    } catch {
      return null;
    }
  };
  const allowed = [...allowedRoots, copy].map(root => root.replace(/\/+$/, ''));
  const symlinks = { total: 0, absolute: 0, broken: 0, outside: [], into_source: [] };
  const inodes = { checked: 0, shared: [] };
  const queue = [copy];
  const seen = new Set();
  while (queue.length) {
    const dir = queue.pop();
    if (seen.has(dir)) continue;
    seen.add(dir);
    let listing;
    try {
      listing = readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of listing) {
      const full = join(dir, entry.name);
      const relative = full.slice(copy.length + 1);
      if (entry.isSymbolicLink()) {
        symlinks.total += 1;
        const raw = readlinkSync(full);
        if (raw.startsWith('/')) symlinks.absolute += 1;
        const resolved = canonical(full);
        if (resolved === null) {
          symlinks.broken += 1;
          continue;
        }
        const within = allowed.some(root => resolved === root || resolved.startsWith(`${root}/`));
        if (!within) {
          symlinks.outside.push({ link: relative, target: resolved });
          if (resolved.startsWith(`${source}/`)) symlinks.into_source.push({ link: relative, target: resolved });
        }
      } else if (entry.isDirectory()) {
        if (entry.name === 'node_modules') continue;
        queue.push(full);
      } else if (entry.isFile()) {
        const sourcePath = join(source, relative);
        let sourceStat;
        try {
          sourceStat = statSync(sourcePath);
        } catch {
          continue;
        }
        inodes.checked += 1;
        const copyStat = statSync(full);
        if (sourceStat.dev === copyStat.dev && sourceStat.ino === copyStat.ino) inodes.shared.push(relative);
      }
    }
  }
  const violations = [];
  if (symlinks.into_source.length) {
    violations.push(`${symlinks.into_source.length} symlink(s) resolve into the source repository, e.g. ${symlinks.into_source.slice(0, 3).map(entry => `${entry.link} → ${entry.target}`).join(', ')}`);
  }
  const outsideOnly = symlinks.outside.filter(entry => !entry.target.startsWith(`${source}/`));
  if (outsideOnly.length) {
    violations.push(`${outsideOnly.length} symlink(s) leave the copy and the allowed roots, e.g. ${outsideOnly.slice(0, 3).map(entry => `${entry.link} → ${entry.target}`).join(', ')}`);
  }
  if (inodes.shared.length) {
    violations.push(`${inodes.shared.length} file(s) share an inode with the source (hardlink), e.g. ${inodes.shared.slice(0, 3).join(', ')}`);
  }
  if (violations.length) {
    throw new Error(`workspace copy is not isolated: ${violations.join('; ')}`);
  }
  return { symlinks, inodes, allowed_roots: allowed, source, copy };
}

async function runChecks(context) {
  const module = await loadChecksModule(context.caseDef.id);
  if (!module?.run) {
    return { checks: [{ name: 'checks-module', passed: false, evidence: `no checks module for ${context.caseDef.id}` }], scenario_status: 'UNKNOWN' };
  }
  return module.run(context);
}

/**
 * Final classification for one run.
 *
 * Order matters: the scenario's own verdict and the evidence-derived class are
 * settled first, budget exhaustion may only *explain* a scenario failure, and a
 * mechanism failure always wins — a spent budget is not an excuse for broken
 * plumbing, and a broken mechanism is not excused by a small spend.
 */
/**
 * The measured clock and the structured limit evidence, set on the report
 * *before* the case's own checks run.
 *
 * The scale checks read `report.wall_time_ms` and `report.limit_reached` while
 * they derive their class; measuring both only after they had run left those
 * branches comparing against an unset clock and a null limit, and their verdict
 * was then preserved by the classifier. One measurement, taken once, before.
 */
export function measureRun(report, { startedAt = null, clock = Date.now(), budget = null, usage = null, clusterReason = null, refusals = null, buildHashes = null } = {}) {
  const finished = clock;
  if (startedAt !== null) {
    report.finished_at = new Date(finished).toISOString();
    report.wall_time_ms = finished - startedAt;
  }
  // The build fingerprint is compared here as well as at the end of the run: the
  // case checks need to know whether the sources moved under them, and they run
  // before the final comparison.
  if (buildHashes) {
    const drift = buildDrift(report.build_hashes, buildHashes);
    report.build_drift = drift;
    if (drift) report.not_comparable = true;
  }
  const classification = classifyOutcome({
    failureClass: report.failure_class ?? null,
    scenarioStatus: report.scenario_status ?? null,
    budget: budget ?? report.spec?.budget ?? {},
    usage: usage ?? report.ledger?.usage ?? {},
    wallTimeMs: report.wall_time_ms ?? 0,
    clusterReason,
    refusals,
  });
  report.limit_reached = classification.limit_reached;
  report.budget_proximity = classification.budget_proximity;
  return report;
}

export function classifyOutcome({ failureClass, scenarioStatus, budget, usage, wallTimeMs, clusterReason = null, refusals = null }) {
  const tokens = usage?.total_tokens ?? 0;
  const requests = usage?.requests ?? 0;
  // Proximity is *reported*, never used as the cause: 95 of 100 requests leaves
  // five legal sends, and ordinary stagnation can happen there.
  const proximity = {
    tokens: (budget.tokens ?? Infinity) === Infinity ? null : Number((tokens / budget.tokens).toFixed(4)),
    requests: (budget.model_requests ?? Infinity) === Infinity ? null : Number((requests / budget.model_requests).toFixed(4)),
    wall: (budget.wall_time_ms ?? Infinity) === Infinity ? null : Number((wallTimeMs / budget.wall_time_ms).toFixed(4)),
  };
  const structured = Array.isArray(refusals)
    ? refusals.filter(entry => entry && typeof entry.scope === 'string' && entry.scope && typeof entry.dimension === 'string' && entry.dimension)
    : [];
  // `blockedOnBudget` is only ever derived from structured records: a persisted
  // refusal naming its scope and dimension, or the cluster's own persistent stop
  // reason in its coded form. A model's prose about "exhausting attempts" is not
  // evidence that a budget limit was reached.
  const codedReason = typeof clusterReason === 'string' && /^\s*(BUDGET|LIMIT_REACHED):/.test(clusterReason);
  const blockedOnBudget = structured.length > 0 || codedReason;
  const hitWall = wallTimeMs >= (budget.wall_time_ms ?? Infinity);
  const exhausted = {
    tokens: (budget.tokens ?? Infinity) !== Infinity && tokens >= budget.tokens,
    requests: (budget.model_requests ?? Infinity) !== Infinity && requests >= budget.model_requests,
    wall: hitWall,
  };
  const limitReached = Boolean(blockedOnBudget || exhausted.tokens || exhausted.requests || hitWall);
  // A class that a check derived is final: the budget branch may only supply a
  // default when nothing was derived. `limit_reached` carries the structured
  // facts either way, so the tier checks can reach their own verdict.
  const resolved = failureClass ?? (scenarioStatus === 'FAILED' ? (limitReached ? 'LIMIT_REACHED' : 'MODEL_OUTPUT') : null);
  return {
    failure_class: resolved,
    limit_reached: limitReached
      ? {
        hitWall, blockedOnBudget, refusals: structured,
        exhausted, tokens, requests, cluster_reason: clusterReason, proximity,
      }
      : null,
    budget_proximity: proximity,
  };
}

export function mechanismVerdict(report, ledger) {
  const notes = [];
  const unmeasured = [];
  const notExercised = [];
  const record = verdict => {
    report.unmeasured_invariants = unmeasured;
    report.not_exercised_invariants = notExercised;
    report.mechanism_notes = notes;
    return verdict;
  };
  // Name every invariant this run could not measure *before* any early return,
  // so an aggregate verdict never implies an unchecked invariant. A run that
  // never created the opportunity is reported as *not exercised* with the
  // reason, which is a different fact from a measurement that failed — and is
  // never silently promoted to a pass.
  if (ledger.cross_scope_writes === null) {
    if (ledger.cross_scope_writes_state === 'not_exercised') {
      notExercised.push(`write-scope enforcement: ${ledger.settled_writes ?? 0} settled write-capable call(s); this scenario's work is read-only, so the write contract is proven by the cases that write`);
    } else {
      unmeasured.push('write-scope enforcement (settled write-capable calls could not all be checked against a granted scope)');
    }
  }
  if (ledger.granted_scope_overlaps === null) unmeasured.push('granted write-scope overlap');
  if (ledger.llm_inflight_over_limit === null) unmeasured.push('LLM in-flight ceiling');
  if (ledger.resident_handles_over_limit === null) unmeasured.push('resident turn-handle ceiling');
  if (report.failure_class === 'MECHANISM') return record('FAIL');
  if (ledger.duplicate_accepts > 0) notes.push(`duplicate accepts: ${ledger.duplicate_accepts}`);
  if (ledger.duplicate_charges > 0) notes.push(`duplicate usage charges: ${ledger.duplicate_charges}`);
  if (ledger.double_leases > 0) notes.push(`double leases: ${ledger.double_leases}`);
  if (ledger.granted_scope_overlaps > 0) notes.push(`overlapping granted write scopes: ${ledger.granted_scope_overlaps}`);
  if ((ledger.write_scope_refusals ?? 0) > 0) notes.push(`refused out-of-scope writes: ${ledger.write_scope_refusals} (enforcement held)`);
  if (ledger.cross_scope_writes > 0) notes.push(`writes that escaped their granted scope: ${ledger.cross_scope_writes}`);
  if (ledger.lost_transactions > 0) notes.push(`transactions without a terminal state: ${ledger.lost_transactions}`);
  if (ledger.resident_handles_over_limit) notes.push('resident turn handles exceeded max_active_agents');
  if (ledger.llm_inflight_over_limit) notes.push('LLM in-flight exceeded max_llm_concurrency');
  // An unmeasured invariant is never evidence of a pass: name it and withhold
  // the aggregate verdict.
  if (!ledger.available) return record('UNKNOWN');
  // Only a defect fails the verdict: a refused write is recorded above as a fact
  // of enforcement, and the note list would otherwise turn it into a failure.
  const defects = notes.filter(note => !/enforcement held/.test(note));
  if (defects.length) return record('FAIL');
  return record(unmeasured.length ? 'UNKNOWN' : 'PASS');
}

/** Read the durable ledger directly from the run's own cluster.sqlite. */
export function readStoneLedger(layout, clusterId) {
  const db = join(layout.data, 'cluster.sqlite');
  if (!existsSync(db)) return { available: false, reason: 'cluster.sqlite not found' };
  const script = `
    const { DatabaseSync } = require('node:sqlite');
    const db = new DatabaseSync(process.argv[1], { readOnly: true });
    const all = (sql, ...args) => db.prepare(sql).all(...args);
    const cluster = process.argv[2] || null;
    const out = { available: true };
    if (!cluster) { process.stdout.write(JSON.stringify(out)); process.exit(0); }
    out.clusters = all('SELECT id,status,revision,limits,budget,declared_limits FROM clusters WHERE id=?', cluster);
    out.usage = all("SELECT COUNT(*) AS requests, SUM(COALESCE(total_tokens,0)) AS total_tokens, SUM(COALESCE(prompt_tokens,0)) AS prompt_tokens, SUM(COALESCE(completion_tokens,0)) AS completion_tokens, SUM(COALESCE(cached_tokens,0)) AS cached_tokens, SUM(COALESCE(reasoning_tokens,0)) AS reasoning_tokens, SUM(CASE WHEN status='UNKNOWN' THEN 1 ELSE 0 END) AS unknown_requests, SUM(COALESCE(overshoot,0)) AS overshoot FROM usage_receipts WHERE cluster_id=?", cluster)[0];
    out.usage_by_role = all('SELECT role,kind,COUNT(*) AS c,SUM(COALESCE(total_tokens,0)) AS tokens FROM usage_receipts WHERE cluster_id=? GROUP BY role,kind', cluster);
    // Per identity, so a case can hold each Worker to its own allowance.
    out.usage_by_agent = all("SELECT agent_id, role, kind, COUNT(*) AS c, SUM(CASE WHEN status<>'NOT_SENT' THEN 1 ELSE 0 END) AS sent FROM usage_receipts WHERE cluster_id=? GROUP BY agent_id, role, kind", cluster);
    // Every receipt's terminal state, and whether an unknown-cost one recorded
    // why: "accounted" is a property of the ledger, not of the provider.
    out.usage_states = all('SELECT status, COUNT(*) AS c FROM usage_receipts WHERE cluster_id=? GROUP BY status', cluster);
    // The receipt rows themselves: a crash report has to name the exact requests
    // that were dispatched and never settled, not an allowance for them.
    out.usage_rows = all('SELECT request_id,agent_id,role,kind,status,created,settled FROM usage_receipts WHERE cluster_id=? ORDER BY created,request_id', cluster);
    out.usage_unknown_without_note = all("SELECT COUNT(*) AS c FROM usage_receipts WHERE cluster_id=? AND status='UNKNOWN' AND (note IS NULL OR note='')", cluster)[0]?.c ?? 0;
    out.transactions_by_status = all('SELECT status,COUNT(*) AS c FROM transactions WHERE cluster_id=? GROUP BY status', cluster);
    out.transactions_detail = all('SELECT id,node_id,status,revision FROM transactions WHERE cluster_id=? ORDER BY created,id', cluster);
    out.agents = all("SELECT COUNT(*) AS c, SUM(CASE WHEN status<>'TERMINATED' THEN 1 ELSE 0 END) AS live, SUM(CASE WHEN turns>0 THEN 1 ELSE 0 END) AS activated, SUM(turns) AS turns FROM agents WHERE cluster_id=?", cluster)[0];
    // Per-identity session and allocation facts: a check that claims "this
    // Worker's own tool call produced this number" needs the session of the
    // identity the transaction was allocated to, not a reconstructed guess.
    out.agent_sessions = all('SELECT id,role,node_id,session_id,status,turns FROM agents WHERE cluster_id=?', cluster);
    out.allocations = all('SELECT id,agent_id,transaction_id,node_id,write_scope,write_scope_canonical,status,created FROM allocations WHERE cluster_id=?', cluster);
    out.agents_by_role = all('SELECT role,COUNT(*) AS c,SUM(CASE WHEN turns>0 THEN 1 ELSE 0 END) AS activated FROM agents WHERE cluster_id=? GROUP BY role', cluster);
    out.nodes = all("SELECT COUNT(*) AS c, MAX(depth) AS max_depth, SUM(CASE WHEN kind='management' THEN 1 ELSE 0 END) AS management FROM nodes WHERE cluster_id=?", cluster)[0];
    out.events = all('SELECT COUNT(*) AS c FROM events WHERE cluster_id=?', cluster)[0];
    out.event_seq = all('SELECT MAX(seq) AS seq FROM events WHERE cluster_id=?', cluster)[0]?.seq ?? null;
    out.leases = all('SELECT COUNT(*) AS c FROM leases WHERE cluster_id=?', cluster)[0];
    out.lease_rows = all('SELECT id,cluster_id,agent_id,node_id,purpose,epoch,expires,event_upper_bound,created FROM leases WHERE cluster_id=? ORDER BY id', cluster);
    out.effects = all('SELECT status,COUNT(*) AS c FROM effects WHERE cluster_id=? GROUP BY status', cluster);
    out.audits = all('SELECT kind,decision,COUNT(*) AS c FROM audits WHERE cluster_id=? GROUP BY kind,decision', cluster);
    out.issues = all('SELECT status,COUNT(*) AS c,SUM(corrections) AS corrections FROM issues WHERE cluster_id=? GROUP BY status', cluster);
    out.deliveries = all('SELECT status,COUNT(*) AS c FROM recipients WHERE message_id IN (SELECT id FROM messages WHERE cluster_id=?) GROUP BY status', cluster);
    out.budget_refusals = all("SELECT COUNT(*) AS c FROM events WHERE cluster_id=? AND type IN ('budget-refused','tool-call-refused')", cluster)[0].c;
    out.structured_budget_refusals = all("SELECT json_extract(data,'$.scope') AS scope, json_extract(data,'$.dimension') AS dimension, json_extract(data,'$.agent_id') AS agent_id FROM events WHERE cluster_id=? AND type='budget-refused'", cluster);
    out.blockers = all("SELECT json_extract(data,'$.code') AS code, json_extract(data,'$.reason') AS reason FROM events WHERE cluster_id=? AND type IN ('cluster-blocked','node-blocked')", cluster);
    out.blocked_reason = all("SELECT json_extract(data,'$.reason') AS reason FROM events WHERE cluster_id=? AND type='cluster-blocked' ORDER BY seq DESC LIMIT 1", cluster)[0]?.reason ?? null;
    out.duplicate_accepts = all("SELECT COUNT(*) AS c FROM (SELECT json_extract(data,'$.transaction_id') AS t FROM events WHERE cluster_id=? AND type='result-accepted' GROUP BY t HAVING COUNT(*)>1)", cluster)[0].c;
    out.duplicate_charges = all('SELECT COUNT(*) AS c FROM (SELECT request_id FROM usage_receipts WHERE cluster_id=? GROUP BY request_id HAVING COUNT(*)>1)', cluster)[0].c;
    out.double_leases = all('SELECT COUNT(*) AS c FROM (SELECT agent_id FROM leases WHERE cluster_id=? GROUP BY agent_id HAVING COUNT(*)>1)', cluster)[0].c;
    // Concurrency is *derived* from recorded intervals, never assumed: receipts
    // span one provider request, leases span one resident turn handle.
    const maxOverlap = (rows, from, to) => {
      const points = [];
      for (const row of rows) {
        const start = row[from];
        const end = row[to];
        if (typeof start !== 'number' || typeof end !== 'number') continue;
        points.push([start, 1], [Math.max(start, end), -1]);
      }
      points.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
      let live = 0, peak = 0;
      for (const [, delta] of points) { live += delta; if (live > peak) peak = live; }
      return peak;
    };
    const receipts = all('SELECT created, settled FROM usage_receipts WHERE cluster_id=?', cluster);
    out.max_llm_inflight = receipts.length ? maxOverlap(receipts, 'created', 'settled') : null;
    // Resident turn handles are measured from the durable turn events, not from
    // the lease table: a released lease is deleted, so a finished run has no
    // lease rows left and the interval that actually existed would be
    // unmeasurable exactly when the run succeeded.
    const turnEvents = all("SELECT type,data,at FROM events WHERE cluster_id=? AND type IN ('turn-start','turn-end') ORDER BY seq", cluster);
    const openTurns = new Map();
    const turnIntervals = [];
    for (const row of turnEvents) {
      let agentId = null;
      try { agentId = JSON.parse(row.data).agent_id ?? null; } catch { agentId = null; }
      if (!agentId) continue;
      if (row.type === 'turn-start') openTurns.set(agentId, row.at);
      else if (openTurns.has(agentId)) { turnIntervals.push([openTurns.get(agentId), row.at]); openTurns.delete(agentId); }
    }
    const lastEventAt = all('SELECT MAX(at) AS at FROM events WHERE cluster_id=?', cluster)[0]?.at ?? null;
    for (const [, start] of openTurns) turnIntervals.push([start, lastEventAt ?? start]);
    out.turn_events = turnEvents.length;
    out.max_resident_turns = turnIntervals.length ? maxOverlap(turnIntervals, 0, 1) : null;
    // A granted overlap is a mechanism defect, checked against the *persisted*
    // canonical grants rather than against the strings the grant was made from.
    const allocated = all("SELECT write_scope_canonical FROM allocations WHERE cluster_id=? AND status='ACTIVE'", cluster)
      .map(row => { try { return JSON.parse(row.write_scope_canonical || '[]'); } catch { return []; } })
      .filter(scope => Array.isArray(scope) && scope.length);
    let overlaps = 0;
    for (let i = 0; i < allocated.length; i += 1) {
      for (let j = i + 1; j < allocated.length; j += 1) {
        for (const a of allocated[i]) for (const b of allocated[j]) {
          if (a === b || a.startsWith(b.endsWith('/') ? b : b + '/') || b.startsWith(a.endsWith('/') ? a : a + '/')) overlaps += 1;
        }
      }
    }
    out.granted_scope_overlaps = overlaps;
    out.allocations_with_scope = allocated.length;
    out.terminal_transactions = all("SELECT COUNT(*) AS c FROM transactions WHERE cluster_id=? AND status IN ('ACCEPTED','FAILED','CANCELLED','SUPERSEDED','BLOCKED')", cluster)[0].c;
    out.total_transactions = all('SELECT COUNT(*) AS c FROM transactions WHERE cluster_id=?', cluster)[0].c;
    out.blocked_nodes = all("SELECT COUNT(*) AS c FROM nodes WHERE cluster_id=? AND status='BLOCKED'", cluster)[0].c;
    // Scope enforcement is only *observable* if a write-capable tool actually
    // ran; with no such call the metric is unmeasured, not zero.
    out.write_capable_calls = all("SELECT COUNT(*) AS c FROM effects WHERE cluster_id=? AND tool IN ('write','edit','bash')", cluster)[0].c;
    // A refused attempt is the sandbox *working*; it is reported as its own fact
    // and never as a failure. Whether a write actually escaped its grant needs
    // execution evidence, which the caller derives from the settled effects.
    out.write_scope_refusals = all("SELECT COUNT(*) AS c FROM events WHERE cluster_id=? AND type='write-refused'", cluster)[0].c;
    out.write_allocations = all("SELECT agent_id, write_scope, write_scope_canonical FROM allocations WHERE cluster_id=?", cluster);
    out.write_effects = all("SELECT agent_id, tool, args, status FROM effects WHERE cluster_id=? AND status='SETTLED' AND tool IN ('write','edit')", cluster);
    process.stdout.write(JSON.stringify(out, null, 2));
  `;
  const result = spawnSync(process.execPath, ['-e', script, db, clusterId ?? ''], { encoding: 'utf8', maxBuffer: 1 << 28 });
  if (result.status !== 0) return { available: false, reason: (result.stderr ?? '').slice(-2000) };
  try {
    const parsed = JSON.parse(result.stdout);
    const clusterStatus = parsed.clusters?.[0]?.status ?? 'UNKNOWN';
    const readJson = value => {
      if (value === null || value === undefined) return {};
      try { return typeof value === 'string' ? JSON.parse(value) : value; } catch { return {}; }
    };
    const clusterRow = parsed.clusters?.[0] ?? {};
    // The *declared* limits are the ceiling the run is measured against. A role
    // may lower the live limits mid-run (the Allocator's `set_concurrency`), and
    // comparing a whole run's peak against a limit that was changed after the
    // fact would report a compliant run as a violation.
    const limits = { ...readJson(clusterRow.budget), ...readJson(clusterRow.declared_limits ?? clusterRow.limits) };
    const ceilings = {
      active: Number(limits.max_active_agents) > 0 ? Number(limits.max_active_agents) : null,
      llm: Number(limits.max_llm_concurrency) > 0 ? Number(limits.max_llm_concurrency) : null,
    };
    const unfinished = Math.max(0, (parsed.total_transactions ?? 0) - (parsed.terminal_transactions ?? 0));
    // A prevented write and an escaped write are different facts: the first is
    // the enforcement holding, the second is the defect. Measured here, from the
    // settled effects and the grants they were supposed to obey.
    const writeAnalysis = writeScopeAnalysis({
      allocations: parsed.write_allocations ?? [],
      effects: parsed.write_effects ?? [],
      workspace: layout?.workspace ?? null,
    });
    return {
      ...parsed,
      cluster_status: clusterStatus,
      blocked_reason: parsed.blocked_reason ?? null,
      budget_refusals: parsed.budget_refusals ?? null,
      structured_budget_refusals: (parsed.structured_budget_refusals ?? []).filter(entry => entry.scope && entry.dimension),
      blockers: parsed.blockers ?? [],
      duplicate_accepts: parsed.duplicate_accepts ?? 0,
      duplicate_charges: parsed.duplicate_charges ?? 0,
      double_leases: parsed.double_leases ?? 0,
      // `null` means "not measured in this run"; it is never reported as zero.
      // A proven escape is a failure even when other calls could not be checked;
      // only a clean-but-incomplete result is UNKNOWN. Three states, named: a run
      // that never admitted a write-capable call did not exercise the invariant
      // at all, which is a different fact from a run that could not check one.
      cross_scope_writes: writeAnalysis.escapes.length ? writeAnalysis.escapes.length
        : writeAnalysis.settled_writes === 0 ? null
          : writeAnalysis.unmeasured ? null : 0,
      cross_scope_writes_state: writeAnalysis.escapes.length ? 'measured'
        : writeAnalysis.settled_writes === 0 ? 'not_exercised'
          : writeAnalysis.unmeasured ? 'unknown' : 'measured',
      settled_writes: writeAnalysis.settled_writes ?? 0,
      write_scope_refusals: parsed.write_scope_refusals ?? null,
      write_scope_checked: writeAnalysis.checked,
      granted_scope_overlaps: parsed.granted_scope_overlaps ?? null,
      write_capable_calls: parsed.write_capable_calls ?? null,
      unfinished_at_stop: unfinished,
      // Work left when the cluster was *stopped* by a declared limit is the
      // documented outcome; work left behind by a cluster that claims
      // COMPLETED is a lost transaction.
      lost_transactions: clusterStatus === 'COMPLETED' ? unfinished : 0,
      // Compare against the limits the cluster recorded for itself; without
      // them the ceiling is unmeasured rather than assumed.
      resident_handles_over_limit: parsed.max_resident_turns == null || !ceilings.active
        ? null : parsed.max_resident_turns > ceilings.active,
      llm_inflight_over_limit: parsed.max_llm_inflight == null || !ceilings.llm
        ? null : parsed.max_llm_inflight > ceilings.llm,
      max_resident_turns: parsed.max_resident_turns ?? null,
      max_llm_inflight: parsed.max_llm_inflight ?? null,
      ceilings,
    };
  } catch (error) {
    return { available: false, reason: `ledger parse failed: ${error.message}` };
  }
}

/**
 * Per-request evidence, without the whole prompt: who was addressed, which
 * script branch answered, what the answer contained, and whether it was held.
 * The Authorization header is never recorded at all.
 */
function summarizeMockRequests(mock) {
  return mock.requests.map(entry => ({
    seq: entry.seq, kind: entry.kind, role: entry.role, node_id: entry.node_id, agent_id: entry.agent_id,
    transaction_id: entry.transaction_id, barrier: entry.barrier,
    authorized: entry.authorized, max_tokens_field: entry.request_shape?.max_tokens_field ?? null,
    tool_calls: (entry.response?.tool_calls ?? []).map(call => call.name),
    finish_reason: entry.response?.finish_reason ?? null,
    usage: entry.response?.usage ?? null,
  }));
}

function listSessions(layout) {
  const root = join(layout.home, 'sessions');
  if (!existsSync(root)) return [];
  return walk(root).slice(0, 500);
}

function walk(root) {
  const out = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = join(root, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push({ path: full, bytes: statSync(full).size });
  }
  return out;
}

/** Run only when executed directly: importing this module must have no effect. */
const invokedDirectly = () => {
  const entry = process.argv[1];
  if (!entry) return false;
  const self = fileURLToPath(import.meta.url);
  try {
    return self === resolve(entry);
  } catch {
    // A missing import must not turn the entry point into a silent no-op.
    return self.endsWith(entry);
  }
};

if (invokedDirectly()) {
  main().catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}
