/** Scoped business-content styles; shell geometry and theme remain provider-owned. */
export const TEAM_CSS = `
.flow-agent-session-header{display:inline-flex;align-items:center;gap:8px;min-width:0}
.flow-session-record{margin:0 24px 20px;padding:16px;border:1px solid var(--dsw-alias-border-l4);border-radius:var(--dsw-radius-lg);background:var(--dsw-alias-bg-layer-1);display:flex;justify-content:center;align-items:center;gap:8px;color:var(--dsw-alias-label-tertiary)}
.flow-session-record strong{color:var(--dsw-alias-label-primary)}

.flow-communication{border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);min-width:0;overflow:hidden}
.flow-communication-header{display:flex;align-items:center;gap:10px;min-height:44px;box-sizing:border-box;padding:10px 14px;cursor:pointer;list-style:none;font-size:13px}.flow-communication-header:hover{background:var(--dsw-alias-interactive-bg-hover)}.flow-communication-header::-webkit-details-marker{display:none}.flow-communication-header:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:-2px}.flow-communication-subject{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:400}.flow-communication-icon{flex-shrink:0;color:var(--dsw-alias-label-secondary)}.flow-communication[data-flow-tone=success] .flow-communication-icon{color:var(--dsw-alias-state-success-primary)}.flow-communication[data-flow-tone=warning] .flow-communication-icon{color:var(--dsw-alias-state-warn-primary)}.flow-communication-chevron{flex-shrink:0;color:var(--dsw-alias-label-tertiary);transform:rotate(-90deg)}.flow-communication[open] .flow-communication-chevron{transform:none}
.flow-communication-detail{margin:0 14px;padding:14px 0;border-top:1px solid var(--dsw-alias-border-l3)}.flow-communication-meta{display:flex;align-items:center;flex-wrap:wrap;gap:6px;font-size:12px;color:var(--dsw-alias-label-secondary)}.flow-communication-meta time{margin-inline-start:auto;font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-tertiary)}.flow-communication-full-subject{margin:12px 0 0;font-size:13px;font-weight:500;overflow-wrap:anywhere}.flow-communication-task{margin:8px 0 0;font-size:11px;color:var(--dsw-alias-label-tertiary);overflow-wrap:anywhere}.flow-communication-body{margin-top:12px;overflow-wrap:anywhere;min-width:0}.flow-communication-body>:first-child{margin-top:0}
.flow-content,.flow-settings,.flow-team-popup{font:inherit;color:var(--dsw-alias-label-primary);min-width:0;box-sizing:border-box}
.flow-content{position:relative;display:flex;flex-direction:column;height:100%;min-height:0;overflow:hidden;container-type:inline-size;background:var(--dsw-alias-bg-base)}
.flow-information h3,.flow-information h4,.flow-detail-heading h3,.flow-node strong,.flow-detail-heading strong,.flow-settings strong{font-weight:500}.flow-information h3,.flow-information h4,.flow-detail-heading h3,.flow-settings p{margin:.3rem 0}
.flow-tree-copy small,.flow-list-row small,.flow-node small,.flow-settings small{color:var(--dsw-alias-label-secondary)}
.flow-toolbar,.flow-actions,.flow-detail-heading{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;min-width:0}
.flow-settings select{font:inherit;color:inherit;background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-sm);padding:.5em;max-width:100%}
.flow-node:focus-visible,.flow-team-popup [role=treeitem]:focus-visible,.flow-settings :focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
.flow-header{display:inline-flex}.flow-team-trigger{font-size:13px!important;color:var(--dsw-alias-label-secondary)!important;gap:6px!important;align-items:center!important}.flow-trigger-state{font-size:12px;color:var(--dsw-alias-label-tertiary)}.flow-trigger-chevron,.flow-tree-chevron{display:block;flex-shrink:0;align-self:center}.flow-team-trigger[aria-expanded=true]>.flow-trigger-chevron{transform:rotate(180deg)}
.flow-team-popup{position:fixed;z-index:var(--dsw-z-popover,50);box-sizing:border-box;width:min(360px,calc(100vw - 32px));max-height:min(420px,65dvh);overflow:auto;padding:8px;font-size:13px;line-height:18px;background:var(--dsw-specific-menu)}
.flow-tree{display:flex;flex-direction:column;gap:2px;user-select:none}.flow-tree-row{display:grid;grid-template-columns:20px minmax(0,1fr);gap:4px;align-items:center;min-width:0;border-radius:var(--dsw-radius-md);padding:6px 2px}.flow-tree-row:hover{background:var(--dsw-alias-interactive-bg-hover)}
.flow-tree-toggle,.flow-tree-leaf{width:20px!important;height:20px!important;min-width:20px!important;min-height:20px!important;padding:0!important;display:inline-flex;align-items:center;justify-content:center;flex-shrink:0}.flow-tree-toggle>svg{display:block}
.flow-tree-copy{min-width:0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:2px 8px}.flow-tree-name{font-size:13px;line-height:20px;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.flow-tree-usage,.flow-tree-time{text-align:right;font-size:12px;font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-tertiary)}.flow-tree-copy .flow-status{font-size:12px;color:var(--dsw-alias-label-tertiary)}.flow-tree-open{display:grid!important;grid-template-columns:minmax(0,1fr) 14px;gap:8px!important;width:100%;height:auto!important;min-height:40px!important;padding:0 8px 0 0!important;text-align:start;white-space:normal;background:transparent!important;color:var(--dsw-alias-label-primary)!important}.flow-tree-chevron{color:var(--dsw-alias-label-tertiary)}.flow-row-state{display:flex;align-items:center;gap:6px;min-width:0;overflow:hidden;font-size:12px}.flow-row-state>.flow-status{flex-shrink:0}.flow-agent-model{display:none;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-tertiary);font-size:12px}.flow-tree-row:hover .flow-agent-model,.flow-list-row:hover .flow-agent-model,.flow-node:hover .flow-agent-model{display:block}.flow-team-footer{display:flex;justify-content:flex-end;border-top:1px solid var(--dsw-alias-border-l3);padding-top:6px;margin-top:6px}
.flow-list-row{user-select:none;display:flex;gap:.5em;align-items:flex-start;min-width:0;border-bottom:1px solid var(--dsw-alias-border-l3);padding:.5em}
.flow-title{justify-content:flex-start!important;max-width:100%;height:auto!important;min-height:2rem;text-align:start;white-space:normal;overflow-wrap:anywhere}.flow-status{display:inline-flex;align-items:center;gap:.4em;flex-wrap:wrap}
.flow-list-row{flex-wrap:wrap;align-items:center}.flow-list-row>.flow-title{flex:1;min-width:8rem}.flow-id{font-family:monospace;overflow-wrap:anywhere;font-size:.85em}
.flow-scroll{overflow:auto;min-height:0;flex:1;scrollbar-gutter:stable}.flow-structure{display:flex;flex-direction:column;flex:1;height:100%;min-height:0}.flow-dock{position:absolute;z-index:4;right:12px;bottom:12px;display:flex;width:min(780px,calc(100% - 24px));height:45%;min-height:220px;max-height:calc(100% - 120px);box-sizing:border-box;background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-lg);box-shadow:0 8px 28px #0002;overflow:hidden;resize:both}
.flow-graph-area{position:relative;flex:1;min-height:0;height:100%}.flow-graph{position:absolute;inset:0;overflow:hidden;touch-action:none;background:radial-gradient(circle,var(--dsw-alias-border-l2) 1px,transparent 1px) 0 0/24px 24px}
.flow-graph-world{position:absolute;transform-origin:top left}.flow-lines{position:absolute;overflow:visible;color:var(--dsw-alias-label-secondary);pointer-events:none}.flow-lines>path{stroke-width:1.75;stroke-linejoin:round;vector-effect:non-scaling-stroke}
.flow-node,.flow-list-row{--flow-role-color:var(--dsw-static-neutral-bluish-500)}
.flow-node[data-role=orchestrator],.flow-list-row[data-role=orchestrator]{--flow-role-color:var(--dsw-static-blue-450)}
.flow-node[data-role=allocator],.flow-list-row[data-role=allocator]{--flow-role-color:var(--dsw-static-green-500)}
.flow-node[data-role=auditor],.flow-list-row[data-role=auditor]{--flow-role-color:var(--dsw-static-amber-500)}
.flow-node[data-role=worker],.flow-list-row[data-role=worker]{--flow-role-color:#9b7ee8}
.flow-node{position:absolute;box-sizing:border-box;width:220px;height:124px;display:flex;flex-direction:column;gap:5px;text-align:start;border:1px solid color-mix(in srgb,var(--flow-role-color) 48%,var(--dsw-alias-bg-base));border-radius:var(--dsw-radius-lg);background:color-mix(in srgb,var(--flow-role-color) 16%,var(--dsw-alias-bg-base));color:var(--dsw-alias-label-primary);padding:12px;font:inherit;cursor:pointer;user-select:none}.flow-node[aria-pressed=true]{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}.flow-node strong,.flow-node small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:100%}
.flow-node-person{display:flex;align-items:center;gap:10px;height:48px;flex-shrink:0}.flow-node-person strong{font-size:16px;font-weight:500}.flow-avatar{display:inline-flex;width:44px;height:44px;border-radius:50%;align-items:center;justify-content:center;background:color-mix(in srgb,var(--flow-role-color) 26%,var(--dsw-alias-bg-base));font-size:26px;line-height:1;flex-shrink:0}.flow-node-meta{position:absolute;top:12px;right:12px;max-width:104px;display:flex;flex-direction:column;gap:3px;align-items:flex-end;font-size:10px;line-height:14px;color:var(--dsw-alias-label-secondary)}.flow-node-meta .flow-row-state{justify-content:flex-end;flex-wrap:wrap;max-width:104px;font-size:10px;gap:2px 4px}.flow-node-meta .flow-agent-model{font-size:10px;max-width:104px}.flow-node-meta .flow-status{font-size:10px}.flow-node-person{max-width:96px}.flow-node-task,.flow-node-usage{font-size:11px;line-height:16px}.flow-node-task{margin-top:4px}.flow-node-usage{font-variant-numeric:tabular-nums}
.flow-list-row[data-role]{background:color-mix(in srgb,var(--flow-role-color) 8%,var(--dsw-alias-bg-base));border-inline-start:3px solid var(--flow-role-color);border-radius:var(--dsw-radius-sm);margin-bottom:4px}
.flow-conversation-detail{display:flex;flex-direction:column;box-sizing:border-box;height:100%;min-height:0;padding:.5rem}.flow-reader{display:flex;flex-direction:column;min-height:0;flex:1}.flow-information{padding:.7rem}.flow-information article{padding:.5em 0;border-bottom:1px solid var(--dsw-alias-border-l3)}
.flow-result pre{white-space:pre-wrap;overflow-wrap:anywhere}.flow-mobile-detail{flex:1;min-height:20rem;overflow:auto}
.flow-reader-actions{display:flex;gap:.5em;flex-wrap:wrap;flex-shrink:0;padding:.4rem 0}.flow-settings{padding:1rem;max-width:50rem}.flow-settings fieldset{display:flex;flex-direction:column;gap:1em;border:0;margin:.8em 0;padding:0}.flow-settings legend{font-weight:500;margin-bottom:.8em}.flow-settings label{display:grid;grid-template-columns:minmax(10em,1fr) minmax(8em,1fr);gap:.3em 1em}.flow-settings small{grid-column:1/-1}
.flow-content[data-reduce-motion=true] *, .flow-content[data-reduce-motion=true] *::before{animation:none!important;transition:none!important}@media(prefers-reduced-motion:reduce){.flow-content *,.flow-team-popup *{animation:none!important;transition:none!important}}
.flow-toolbar,.flow-zoom{position:absolute;z-index:3;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-lg);box-shadow:0 3px 14px #0001;padding:.45rem .6rem}
.flow-toolbar{width:fit-content;max-width:100%;box-sizing:border-box}.flow-toolbar button{white-space:nowrap}
.flow-zoom{bottom:12px;left:12px;z-index:5;font-size:.85em}.flow-zoom>span{width:3em;text-align:center;font-variant-numeric:tabular-nums}.flow-notices{position:absolute;z-index:3;top:12px;right:12px;max-width:30%;max-height:120px;overflow:auto;font-size:.85em;padding:.5em .7em;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);color:var(--dsw-alias-label-secondary)}.flow-notices:empty{display:none}.flow-notices p{margin:.2em 0}.flow-run-reason{margin:0}
.flow-structure>p,.flow-structure>button,.flow-content>.flow-result{position:absolute;z-index:3;left:12px;top:calc(var(--flow-controls-height,48px) + 24px);background:var(--dsw-alias-bg-layer-2);padding:.5em;border-radius:var(--dsw-radius-md)}.flow-structure>[role=list]{padding:calc(var(--flow-controls-height,48px) + 24px) 12px 64px;box-sizing:border-box}
.flow-content>.flow-detail-heading{padding:12px;margin-top:64px;background:var(--dsw-alias-bg-layer-2)}.flow-content>.flow-conversation-detail{flex:1;min-height:0}.flow-detail-heading .flow-id{color:var(--dsw-alias-label-secondary)}

.flow-controls{position:absolute;z-index:3;top:12px;left:12px;right:12px;display:flex;align-items:flex-start;pointer-events:none}.flow-controls>*{pointer-events:auto}.flow-controls .flow-toolbar{position:static}
.flow-content[data-full-details=true]>.flow-controls,.flow-content[data-full-details=true]>.flow-notices{display:none}.flow-content[data-full-details=true]>.flow-detail-heading{margin-top:0;flex-shrink:0}
@container(max-width:700px){.flow-notices{max-width:45%;max-height:70px}.flow-dock{height:55%;max-height:calc(100% - 120px)}.flow-controls button,.flow-zoom button,.flow-list-row button,.flow-detail-heading>button{min-height:2.5rem}.flow-zoom{right:12px;width:fit-content;max-width:calc(100% - 24px)}}
.flow-dock .flow-conversation-detail,.flow-dock .flow-information{background:var(--dsw-alias-bg-base)}
.flow-sidebar-chat{height:100%;min-height:0;display:flex;flex-direction:column;padding:8px;box-sizing:border-box;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base)}
.flow-trigger-chevron,.flow-tree-toggle>svg{transition:transform 160ms ease;transform-origin:center}.flow-tree-toggle[aria-expanded=true]>svg{transform:rotate(90deg)}
.flow-tree-row{grid-template-columns:20px minmax(0,1fr) 28px}.flow-tree-open{display:flex!important;padding:0!important}.flow-tree-copy{width:100%}.flow-tree-aside{width:28px!important;height:28px!important;min-height:28px!important;padding:0!important;justify-content:center}.flow-tree-role{margin-left:6px;font-size:10px;color:var(--dsw-alias-label-tertiary)}
.flow-agent-model{align-items:center;gap:4px}.flow-tree-row:hover .flow-agent-model,.flow-list-row:hover .flow-agent-model,.flow-node:hover .flow-agent-model{display:inline-flex}.flow-model-divider{margin:0 4px;color:var(--dsw-alias-label-tertiary);flex-shrink:0}.flow-model-name{min-width:0;overflow:hidden;text-overflow:ellipsis}.flow-model-effort{font-size:10px;flex-shrink:0;color:var(--dsw-alias-label-tertiary)}.flow-model-logo{display:inline-block;width:13px;height:13px;flex-shrink:0;background:currentColor;mask-size:contain;mask-repeat:no-repeat;mask-position:center}.flow-model-fallback{flex-shrink:0}.flow-node-meta .flow-agent-model{max-width:104px;gap:2px}.flow-node-meta .flow-model-divider{margin:0 1px}
[data-reduce-motion=true] .flow-trigger-chevron,[data-reduce-motion=true] .flow-tree-toggle>svg{transition:none}
@media(prefers-reduced-motion:reduce){.flow-trigger-chevron,.flow-tree-toggle>svg{transition:none}}
.flow-settings-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:16px}.flow-settings-grid label{display:block;min-width:0}.flow-settings-advanced{margin:16px 0}.flow-settings-advanced summary{cursor:pointer;color:var(--dsw-alias-label-secondary);margin-bottom:16px}.flow-settings fieldset>small{font-size:12px;color:var(--dsw-alias-label-tertiary)}
`;
