import { DatabaseSync } from 'node:sqlite';
import { compileWorkflow, resolveNode, bad, integer, object } from './compiler.js';
export { compileWorkflow };
export class Store {
 constructor(path,{now=Date.now}={}) { this.now=now; this.db=new DatabaseSync(path); this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS workflows(id TEXT PRIMARY KEY, revision INTEGER, status TEXT, limits_json TEXT, created INTEGER); CREATE TABLE IF NOT EXISTS nodes(workflow_id TEXT,id TEXT,kind TEXT,needs TEXT,data TEXT,status TEXT,attempt INTEGER DEFAULT 0,epoch INTEGER DEFAULT 0,lease_id TEXT,worker TEXT,expires INTEGER,output TEXT,error TEXT,PRIMARY KEY(workflow_id,id),FOREIGN KEY(workflow_id) REFERENCES workflows(id)); CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY,workflow_id TEXT,type TEXT,data TEXT,at INTEGER); CREATE TABLE IF NOT EXISTS idem(key TEXT PRIMARY KEY,hash TEXT,workflow_id TEXT); CREATE TABLE IF NOT EXISTS result_messages(id TEXT PRIMARY KEY,payload TEXT,response TEXT);`); }
 close(){this.db.close()}
 tx(fn){this.db.exec('BEGIN IMMEDIATE');try{const v=fn();this.db.exec('COMMIT');return v}catch(e){this.db.exec('ROLLBACK');throw e}}
 event(id,type,data={}){this.db.prepare('INSERT INTO events(workflow_id,type,data,at) VALUES(?,?,?,?)').run(id,type,JSON.stringify(data),this.now())}
 submit(w,key){const ir=compileWorkflow(w);if(typeof key!=='string'||!key||key.length>256)bad('Idempotency-Key required');const canonical=JSON.stringify(w);return this.tx(()=>{const old=this.db.prepare('SELECT * FROM idem WHERE key=?').get(key);if(old){if(old.hash!==canonical)bad('Idempotency conflict',409);return this.get(old.workflow_id)}if(this.db.prepare('SELECT 1 FROM workflows WHERE id=?').get(ir.workflowId))bad('Workflow already exists',409);this.db.prepare('INSERT INTO workflows VALUES(?,?,?,?,?)').run(ir.workflowId,1,'running',JSON.stringify(ir.limits),this.now());for(const n of ir.nodes)this.db.prepare('INSERT INTO nodes(workflow_id,id,kind,needs,data,status) VALUES(?,?,?,?,?,?)').run(ir.workflowId,n.id,n.kind,JSON.stringify(n.needs),JSON.stringify(n),'pending');this.db.prepare('INSERT INTO idem VALUES(?,?,?)').run(key,canonical,ir.workflowId);this.event(ir.workflowId,'submitted',{id:ir.workflowId});return this.get(ir.workflowId)})}
 list(){return this.db.prepare('SELECT id FROM workflows ORDER BY created').all().map(x=>this.get(x.id))}
 get(id){const w=this.db.prepare('SELECT * FROM workflows WHERE id=?').get(id);if(!w)return null;return {id:w.id,revision:w.revision,status:w.status,limits:JSON.parse(w.limits_json),nodes:this.db.prepare('SELECT * FROM nodes WHERE workflow_id=? ORDER BY rowid').all(id).map(n=>({id:n.id,kind:n.kind,status:n.status,attempt:n.attempt,epoch:n.epoch,...(n.output?{output:JSON.parse(n.output)}:{}),...(n.error?{error:n.error}:{})}))}}
 events(id){return this.db.prepare('SELECT type,data,at FROM events WHERE workflow_id=? ORDER BY seq').all(id).map(e=>({type:e.type,...JSON.parse(e.data),at:e.at}))}
 control(id,action){return this.tx(()=>{const w=this.db.prepare('SELECT * FROM workflows WHERE id=?').get(id);if(!w)bad('Workflow not found',404);const next={pause:'paused',resume:'running',cancel:'cancelled'}[action];if(!next)bad('Invalid action');if(['succeeded','failed','cancelled'].includes(w.status))bad('Workflow terminal',409);this.db.prepare('UPDATE workflows SET status=? WHERE id=?').run(next,id);if(action==='cancel')this.db.prepare("UPDATE nodes SET status='cancelled',lease_id=NULL WHERE workflow_id=? AND status IN ('pending','leased','running')").run(id);if(action==='resume')this.finish(id);this.event(id,action);return this.get(id)})}
 expireInTx(){const rows=this.db.prepare("SELECT n.*,w.limits_json FROM nodes n JOIN workflows w ON w.id=n.workflow_id WHERE n.status='leased' AND n.expires<=?").all(this.now());for(const n of rows){const max=JSON.parse(n.data).maxAttempts??JSON.parse(n.limits_json).maxAttempts;if(n.attempt>=max){this.db.prepare("UPDATE nodes SET status='failed',lease_id=NULL,worker=NULL,error='lease expired' WHERE workflow_id=? AND id=?").run(n.workflow_id,n.id);this.finish(n.workflow_id)}else this.db.prepare("UPDATE nodes SET status='pending',lease_id=NULL,worker=NULL WHERE workflow_id=? AND id=?").run(n.workflow_id,n.id);this.event(n.workflow_id,'lease-expired',{nodeId:n.id,epoch:n.epoch})}}
 expire(){return this.tx(()=>this.expireInTx())}
 claim({workerId,ttlMs}){if(typeof workerId!=='string'||!workerId||workerId.length>128)bad('Invalid workerId');integer(ttlMs,100,300000,'ttlMs');return this.tx(()=>{this.expireInTx();const rows=this.db.prepare("SELECT n.*,w.limits_json,w.status ws FROM nodes n JOIN workflows w ON w.id=n.workflow_id WHERE n.status='pending' AND w.status='running' ORDER BY w.created,n.rowid").all();for(const n of rows){const busy=this.db.prepare("SELECT COUNT(*) c FROM nodes WHERE workflow_id=? AND status IN ('leased','running')").get(n.workflow_id).c; if(busy>=JSON.parse(n.limits_json).maxConcurrency)continue;const needs=JSON.parse(n.needs), states=this.db.prepare('SELECT * FROM nodes WHERE workflow_id=?').all(n.workflow_id);const dep=needs.map(id=>states.find(x=>x.id===id));if(dep.some(x=>['failed','skipped','cancelled'].includes(x.status))){this.db.prepare("UPDATE nodes SET status='skipped' WHERE workflow_id=? AND id=?").run(n.workflow_id,n.id);continue}if(dep.some(x=>x.status!=='succeeded'))continue;const id=`${n.workflow_id}:${n.id}:${n.epoch+1}:${this.now()}`;const full=JSON.parse(n.data);const resolved=resolveNode(full,states.map(x=>({id:x.id,status:x.status,output:x.output?JSON.parse(x.output):undefined})));this.db.prepare("UPDATE nodes SET status='leased',attempt=attempt+1,epoch=epoch+1,lease_id=?,worker=?,expires=? WHERE workflow_id=? AND id=?").run(id,workerId,this.now()+ttlMs,n.workflow_id,n.id);this.event(n.workflow_id,'claimed',{nodeId:n.id,workerId,epoch:n.epoch+1});return {lease:{id,epoch:n.epoch+1,workerId,workflowId:n.workflow_id,nodeId:n.id,node:resolved,expiresAt:this.now()+ttlMs}}}for(const r of rows)this.finish(r.workflow_id);return {lease:null}})}
 lease(id,p,heartbeat=false){object(p);integer(p.epoch,1,Number.MAX_SAFE_INTEGER,'epoch');if(heartbeat)integer(p.ttlMs,100,300000,'ttlMs');const n=this.db.prepare('SELECT * FROM nodes WHERE lease_id=?').get(id);if(!n||n.worker!==p.workerId||n.epoch!==p.epoch||n.status!=='leased'||n.expires<=this.now())bad('Lease fenced',409);return n}
 heartbeat(id,p){return this.tx(()=>{const n=this.lease(id,p,true);this.db.prepare('UPDATE nodes SET expires=? WHERE lease_id=?').run(this.now()+p.ttlMs,id);return {expiresAt:this.now()+p.ttlMs}})}
 result(id,p){return this.tx(()=>{const payload=JSON.stringify(p);const old=this.db.prepare('SELECT payload,response FROM result_messages WHERE id=?').get(id);if(old){if(old.payload!==payload)bad('Conflicting duplicate result',409);return JSON.parse(old.response)}const n=this.lease(id,p);if(!['succeeded','failed'].includes(p.status))bad('Invalid status');if(p.status==='succeeded')this.db.prepare("UPDATE nodes SET status='succeeded',output=?,lease_id=NULL,worker=NULL WHERE lease_id=?").run(JSON.stringify(p.output??null),id);else{const w=this.db.prepare('SELECT limits_json FROM workflows WHERE id=?').get(n.workflow_id);const spec=JSON.parse(n.data);if(n.attempt<(spec.maxAttempts??JSON.parse(w.limits_json).maxAttempts))this.db.prepare("UPDATE nodes SET status='pending',lease_id=NULL,worker=NULL,error=? WHERE lease_id=?").run(String(p.error??'failed').slice(0,2048),id);else this.db.prepare("UPDATE nodes SET status='failed',lease_id=NULL,worker=NULL,error=? WHERE lease_id=?").run(String(p.error??'failed').slice(0,2048),id)}this.event(n.workflow_id,'result',{nodeId:n.id,status:p.status});this.finish(n.workflow_id);const response=this.get(n.workflow_id);this.db.prepare('INSERT INTO result_messages VALUES(?,?,?)').run(id,payload,JSON.stringify(response));return response})}
 finish(id){let changed=true;while(changed){changed=false;for(const n of this.db.prepare("SELECT * FROM nodes WHERE workflow_id=? AND status='pending'").all(id)){if(JSON.parse(n.needs).some(dep=>{const x=this.db.prepare('SELECT status FROM nodes WHERE workflow_id=? AND id=?').get(id,dep);return x&&['failed','skipped','cancelled'].includes(x.status)})){this.db.prepare("UPDATE nodes SET status='skipped' WHERE workflow_id=? AND id=?").run(id,n.id);changed=true}}}const w=this.db.prepare('SELECT status FROM workflows WHERE id=?').get(id);if(!w||w.status!=='running')return;const ns=this.db.prepare('SELECT status FROM nodes WHERE workflow_id=?').all(id);if(ns.every(n=>['succeeded','skipped','failed','cancelled'].includes(n.status))){const failed=ns.some(n=>['failed','skipped','cancelled'].includes(n.status));this.db.prepare('UPDATE workflows SET status=? WHERE id=?').run(failed?'failed':'succeeded',id)}}
}
